#+LATEX_CLASS: thesis
#+OPTIONS: title:nil
#+OPTIONS: toc:nil

#+begin_src emacs-lisp :exports none :results none
  (add-to-list 'org-latex-classes
               '("thesis"
                 "\\documentclass{ustcthesis}\\input{ustcsetup.tex}
                  [NO-DEFAULT-PACKAGES]
                  [NO-PACKAGES]"
                 ("\\chapter{%s}" . "\\chapter*{%s}")
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
  (setq org-latex-pdf-process
        '("xelatex -interaction nonstopmode -output-directory %o %f"
          "bibtex %b"
          "xelatex -interaction nonstopmode -output-directory %o %f"
          "xelatex -interaction nonstopmode -output-directory %o %f"))
  (setq org-format-latex-options (plist-put org-format-latex-options :scale 4.0))
#+end_src

#+begin_export latex
\maketitle
\copyrightpage
\frontmatter
#+end_export

#+begin_export latex
\ustcsetup{
  keywords  = {张量网络态，强关联系统，量子多体问题，投影纠缠对态},
  keywords* = {Tensor network state, Strongly correlated systems, Quantum many-body problems, PEPS},
}
#+end_export

#+begin_export latex
\begin{abstract}
摘要 TODO
\end{abstract}

\begin{abstract*}
abstract TODO
\end{abstract*}
#+end_export

#+begin_export latex
\tableofcontents
\listoffigures
\listoftables
#+end_export

* 主要符号对照表

#+begin_export latex
\newenvironment{ustcnotation}{\begin{notation}\begin{notationlist}{2em}}{\end{notationlist}\end{notation}}
#+end_export

#+attr_latex: :environment ustcnotation
- ED :: 严格对角化 (Exact Diagonalization)
- QMC :: 量子蒙特卡洛方法 (Quantum Monte Carlo)
- Ansatz :: 拟设 (Ansatz)
- TNS :: 张量网络态 (Tensor Network States)
- MPS :: 矩阵乘积态 (Matrix Product States)
- PEPS :: 投影纠缠对态 (Projected Entangled Pair States)
- iTEBD :: 逐块虚时间演化 (Imaginary Time-evolving Block Decimation)
- SU :: 简单更新 (Simple Update)
- DMRG :: 密度矩阵重整化 (Density Matrix Renormalization Group)

TODO

#+begin_export latex
\mainmatter
#+end_export

* 绪论 <<sec:绪论>>

上世纪发展的郎道费米液体理论和基于自发对称性破缺的相变理论在强关联系统中失效。
在这种系统中，粒子之间的相互作用非常强，使得传统微扰方法难以给出准确结果。
因此，对这类系统的性质分析主要依赖于数值方法。
故发展针对强关联系统的数值方法成了近年来备受关注的研究方向之一。

强关联系统的数值求解受制于巨大的希尔伯特空间维度，其随着系统尺寸增大而呈指数增长。
因此，传统严格对角化(ED)方法仅适用于约30个格点的有限系统求解。
在某些特殊的强关联系统中，量子蒙特卡洛方法(QMC)能够给出优异结果，但有阻错的系统存在符号问题，为了收敛它依然必须指数增加采样量。
另一大类方法则使用拟设(ansatz)函数来表示波函数，如何用有限数据量表示庞大的希尔伯特空间中的向量是这类数值方法的出发点。

近年来，除了一些传统的有偏拟设和神经网络态拟设，张量网络态(TNS)拟设备受到极大关注。
2003年，Vidal提出了矩阵乘积态作为最早的张量网络态 [[cite:Vidal2003]] 。
这种方法使用一维张量链来表示一维系统的波函数，特别适合满足纠缠熵面积定律的系统。
Verstaete随后将其推广至二维系统，即投影纠缠对态(PEPS) [[cite:Verstraete2004]] ，同样适用于满足面积定律的二维系统。
Vidal针对矩阵乘积态提出了逐块虚时间演化算法(iTEBD) [[cite:Vidal2004,Vidal2007]] ，能有效获得一维系统的基态。
然而在处理二维系统时，优化投影纠缠态变得十分困难，逐块虚时间演化算法难以获得精确结果。
2008年，向涛通过在二维系统逐块虚时间演化算法中引入简单环境得到简单更新(SU)方法 [[cite:Jiang2008]] ，实现在计算效率不减的情况下近似获得基态结果。
获得系统基态后，为计算相关物理量观测值，需要对二维双层张量网络进行收缩。
Sandvik于2007年提出了采样方法 [[cite:Sandvik2007]] ，通过仅收缩二维单层张量网络，便能计算观测量。
2017年，采样方法被用于计算能量梯度 [[cite:Liu2017]] ，从而可用采样方法直接优化拟设波函数。
近几年，直接采样方法 [[cite:Vieijra2021]] 和自然梯度法 [[cite:Neuscamman2012]] 被引入，极大提升了采样效率和优化效率。

本论文将介绍近些年我们对基于采样的张量网络方法的发展与应用。主要结构安排如下：
+ 第 [[ref:sec:绪论]] 章绪论，即本章。
+ 第 [[ref:sec:张量和张量网络]] 章详细介绍张量和张量网络的基础理论。
+ 第 [[ref:sec:张量网络态的优化方法]] 章介绍多种张量网络态的优化方法。

本论文将一直使用爱因斯坦求和约定。本论文将一直从 $0$ 开始计数而不是 $1$ 开始计数。

* 张量和张量网络 <<sec:张量和张量网络>>

** 矩阵乘积态 (MPS)

*** MPS的表示

数值模拟量子多体问题的根本困难在于系统的希尔伯特空间的维度随着系统尺寸的增大指数上升。
比如对于自旋系统，由 $N$ 个自旋 $\frac{1}{2}$ 的粒子构成的格点有 $2^N$ 维的希尔伯特空间，为了表示这个系统的状态，需要 $2^N$ 维的向量作为波函数。
所以不做任何近似的严格表示这个波函数，并精确求解系统的本征态，只能处理很小的系统。
而White在1992年提出了密度矩阵重整化(DMRG)方法 [[cite:White1992]] 成功地求解了各种一维模型的低能态性质。
后来Vidal提出矩阵乘积态(MPS) [[cite:Vidal2003]] ，人们认识到DMRG方法可以被认为是对MPS表示的波函数进行优化的过程。

首先介绍一下张量，它可以被简单地认为是多个线性空间上的多线性映射：
\begin{equation}
\hat T : V_0 \otimes V_1 \otimes V_2 \cdots V_{\mathrm{rank}(T)-1} \to \mathbb{K} .
\end{equation}
其中 $V_r$ 是 $\mathbb{K}$ 上的线性空间， $r=0,1,2,\cdots \mathrm{rank}(T)-1$ 。
而本论文中， $\mathbb{K}$ 只会取 $\mathbb{R}$ 或者 $\mathbb{C}$ ， $V_r$ 也一定是定义了内积的有限维线性空间，
所以可以使用一个高维数组来表示一个张量，即
\begin{equation}
\hat T (
\sum_{i_0=0}^{D_0-1} a_0^{i_0} e_0^{i_0},
\sum_{i_1=0}^{D_1-1} a_1^{i_1} e_1^{i_1},
\cdots
\def\rrr{{R-1}}
\sum_{i_\rrr=0}^{D_{R-1}-1} a_\rrr^{i_\rrr} e_\rrr^{i_\rrr}
)
=
T^{i_0,i_1,\cdots,i_\rrr} a_0^{i_0} a_1^{i_1} \cdots a_\rrr^{i_\rrr},
\end{equation}
其中 $D_r = \mathrm{dim}(V_r)$ ， 而 $R=\mathrm{rank}(T)$ 。
为了表达上的简便，我们直接称呼 $T$ 为张量。

MPS使用一个张量链来表示高维的向量。
以自旋 $\frac{1}{2}$ 系统为例子，一个长度为 $L$ 的自旋系统波函数
\begin{equation}\label{eq:一维系统波函数}
|\Psi\rangle = T^{\sigma_0,\sigma_1,\cdots,\sigma_{L-1}} |\sigma_0 \sigma_1 \cdots \sigma_{L-1}\rangle ,
\end{equation}
可以被使用MPS来表示：
\begin{equation}\label{eq:一维系统波函数的MPS展开}
T^{\sigma_0,\sigma_1,\cdots,\sigma_{L-1}} =
(A_0 ^ {\sigma_0})_{v_1}
(A_1 ^ {\sigma_1})_{v_1 v_2}
(A_2 ^ {\sigma_2})_{v_2 v_3}
\cdots (A_{L-1} ^ {\sigma_{N-1}})_{v_{N-1}} ,
\end{equation}
其中 $\sigma_i$ 为第 $i$ 个格点处的自旋，可以取 $\uparrow$ 或者 $\downarrow$。
从公式 [[eqref:eq:一维系统波函数的MPS展开]] 中看到，MPS表示的波函数在一个构型下的分量，是一连串的矩阵乘积，这是矩阵乘积态(MPS)名称由来。

在MPS表示中，除了最左边和最右边的格点外，第 $i$ 个格点处的 $(A_i^{\sigma_i})_{v_i v_{i+1}}$ 是一个三阶张量，它有一个物理指标 $\sigma_i$
和两个虚拟指标 $v_i$ 和 $v_{i+1}$ 。
其中物理指标 $\sigma_i$ 可以取 $\uparrow$ 或者 $\downarrow$，其维度是 $2$ ，通常使用 $d$ 标记。
而虚拟指标的维度是一个可调节的参数，通常用 $D$ 表示。
这些指标被称作虚拟指标是因为他们并不是真正的物理指标。
对于其他类型的系统，一个格点处的物理维度并不一定是 $2$ ，如tJ模型 $d=3$ ， Hubbard模型 $d=4$ 。

*** 面积定律与MPS

在 $D$ 不变的情况下，MPS可以使用随着系统尺寸线性上升的参数来表示维度指数上升的波函数。
而固定 $D$ 的MPS正合适表示满足纠缠熵面积定律的态。

一个量子态分割成两个部分A和B后，A部分和B部分之间的纠缠熵是
\begin{equation}\label{eq:纠缠熵}
S_{A|B} = - \mathrm{tr} (\hat\rho_A \ln \hat\rho_A) = - \mathrm{tr} (\hat\rho_B \ln \hat\rho_B) = - \sum_{v=0}^{V-1} \lambda_v \ln \lambda_v,
\end{equation}
其中 $\hat\rho_A$ 和 $\hat\rho_B$ 是A部分和B部分的约化密度矩阵，$\lambda_v$ 是他们的本征值， $V$ 为约化密度矩阵的维度。
纠缠熵最大的情况下，所有的本征值相等，即 $\lambda_v = \frac{1}{V}$，此时 $S_{A|B} = \ln V$ 。
而约化密度矩阵的维度随着较小系统的尺寸指数上升，不妨假设A部分比B部分更小， 有$S_{A|B} \propto |A|$ ，其中 $|A|$ 为A部分的体积。
而当系统满足纠缠熵面积定律时，纠缠熵有更强的约束， 即
\begin{equation}\label{eq:面积定律}
S_{A|B} \propto |\partial A| = |\partial B|,
\end{equation}
其中 $|\partial X|$ 表示X的边界大小。

对于公式 [[eqref:eq:一维系统波函数的MPS展开]] 表示的MPS， 切割为长度为 $X$ 和 $Y$ 的两部分， $X+Y=L$ ，X部分的约化密度矩阵为
\begin{equation}\label{eq:MPS切割后的约化密度矩阵}
\begin{aligned}
(\hat\rho_X)_{\sigma_0,\sigma_1,\cdots,\sigma_{X-1}}^{\sigma'_0,\sigma_2,\cdots,\sigma'_{X-1}} =&
(A_0 ^ {\sigma_0})_{v_1}
\cdots
(A_{X-1} ^ {\sigma_{X-1}})_{v_{X-1} v_X}
(A_X ^ {\sigma_X})_{v_X v_{X+1}}
\cdots
(A_{L-1} ^ {\sigma_{N-1}})_{v_{N-1}}
\\
&
(A_0 ^ {\sigma'_0})^\dag_{v'_1}
\cdots
(A_{X-1} ^ {\sigma'_{X-1}})^\dag_{v'_{X-1} v'_X}
(A_X ^ {\sigma_X})^\dag_{v'_X v'_{X+1}}
\cdots
(A_{L-1} ^ {\sigma_{N-1}})^\dag_{v'_{N-1}} .
\end{aligned}
\end{equation}
注意到
\begin{equation}
\begin{aligned}
(\hat\rho_X)_{\sigma_0,\sigma_1,\cdots,\sigma_{X-1}}^{\sigma'_0,\sigma_2,\cdots,\sigma'_{X-1}} =&
(A_0 ^ {\sigma_0})_{v_1}
\cdots
(A_{X-1} ^ {\sigma_{X-1}})_{v_{X-1} v_X}
\\
&
M_{v_X, v_X'}
\\
&
(A_0 ^ {\sigma'_0})^\dag_{v'_1}
\cdots
(A_{X-1} ^ {\sigma'_{X-1}})^\dag_{v'_{X-1} v'_X},
\end{aligned}
\end{equation}
其中
\begin{equation}
\begin{aligned}
M_{v_X, v_X'} =&
(A_X ^ {\sigma_X})_{v_X v_{X+1}}
\cdots
(A_{L-1} ^ {\sigma_{N-1}})_{v_{N-1}}
\\
&
(A_X ^ {\sigma_X})^\dag_{v'_X v'_{X+1}}
\cdots
(A_{L-1} ^ {\sigma_{N-1}})^\dag_{v'_{N-1}} ,
\end{aligned}
\end{equation}
而 $M_{v_X,v'_X}$ 是一个 $D \times D$ 的矩阵，所以密度矩阵 $\hat \rho_X$ 的秩不大于 $D$ ，则其可表示的最大纠缠熵为 $S = \ln D$ ，即一个常数。
而满足纠缠熵面积定律的一维系统，两部分的边界是零维的点，大小也是常数，所以MPS表示的一维系统恰好是满足一维情况下面积定律的系统。

由于MPS对面积定律恰到好处的展示，MPS可以较高效地表示满足纠缠熵面积定律的系统的波函数。
一维情况下，局部哈密顿量构成的有能隙系统的基态是满足面积定律的，所以一个固定 $D$ 的MPS可以很好地表示其基态。
而对于无能隙的系统，有 $S \propto \alpha \ln L$ ，即纠缠熵随着系统的尺寸对数上升，而 $ S \propto \ln D$ ，所以应取 $D \propto L ^\alpha$ ，
对于 $\alpha$ 较小的情况， 所需的 $D$ 随着系统尺寸增长缓慢，我们依然可以通过计算相当大的系统来了解接近热力学极限时系统的性质。

*** 张量网络的图形标记

由于张量网络态中各个张量通常有复杂的运算关系，使用爱因斯坦求和约定不能直观地展示张量之间的关系，人们通常使用图形标记法来表示一张张量网络。
图形标记法中，使用一个闭合的图形表示一个张量，图形上的每一条线表示张量的一个指标，两个张量之间彼此相连的线表示这两个指标将要求和。
图 [[ref:fig:张量的图形标记法]] 中展示了一些基本的例子。

#+begin_export latex
\begin{figure}
\centering
\input{tikz/graphical_notation.tikz}
\caption{张量的图形标记法}
\label{fig:张量的图形标记法}
\note{注：
(a)是一个标量 $A$ ，即0阶张量；
(b)是一个向量 $A_i$ ，即1阶张量，有一个指标 $i$ ；
(c)是一个矩阵 $A_{ij}$ ，即2阶张量，有两个指标 $i$ 和 $j$ ；
(d)表示矩阵 $A_{ij}$ 和向量 $B_j$ 的乘积，即 $A_{ij} B_{j}$ ；
(e)表示两个矩阵相乘，即 $A_{ij} B_{jk}$ ；
(f)中三个矩阵彼此相连，表示了 $A_{ij} B_{jk} C_{ji}$ 。
}
\end{figure}
#+end_export

使用图形标记法表示的公式 [[eqref:eq:一维系统波函数的MPS展开]] 所展示的MPS在 $L=5$ 时如图 [[ref:fig:图形标记法表示的长度为5的MPS]] 所示。
张量网络的图形标记法直观地展示了张量之间的连接关系。

#+begin_export latex
\begin{figure}
\centering
\input{tikz/mps.tikz}
\caption{图形标记法表示的长度为$5$的MPS}
\label{fig:图形标记法表示的长度为5的MPS}
\end{figure}
#+end_export

** 投影纠缠对态 (PEPS)

*** PEPS的表示

MPS成功地处理一维系统后，有一些将MPS直接应用于二维系统的尝试，如图 [[ref:fig:用于表示二维系统的MPS和PEPS]] (a)所示。
但是二维系统中，对于满足纠缠熵面积定律的系统，纠缠熵 $S \propto L$ ，其中 $L$ 为边界的长度。
这意味这MPS的 $D$ 需要随着系统增大而增大。
时至今日，这种方法通常被用于长条形的系统的求解，而对于真正的二维系统，MPS无法胜任。
Verstraete在表示二维系统的MPS上额外上了行间的边从而得到了PEPS [[cite:Verstraete2004]] ，如图 [[ref:fig:用于表示二维系统的MPS和PEPS]] (b)所示。
我们称呼物理指标所在的边为物理边，其他张量之间彼此相连的边为虚拟边。

#+begin_export latex
\begin{figure}
\centering
\input{tikz/mps_to_peps.tikz}
\caption{用于表示二维系统的MPS和PEPS}
\label{fig:用于表示二维系统的MPS和PEPS}
\note{注：由于固定 $D$ 的MPS只能表示常数的纠缠熵，通过在行间加上而外的边可以得到PEPS，PEPS可以满足二维系统的面积定律。}
\end{figure}
#+end_export

一张PEPS中划分出一个区域X，其与外界相连的边的数目正比与区域的周长，即边的数目 $N \propto |\partial X|$ 。
类似MPS的情况，计算约化密度矩阵时有同样的形式：
\begin{equation}\label{eq:PEPS中计算约化密度矩阵}
(\hat\rho_{X})_{s_{X, 0}, s_{X, 1}, \cdots} ^ {s'_{X, 0}, s'_{X, 1}, \cdots} =
T_{s_{X,0}, s_{X,1}, \cdots}^{v_0, v_1, \cdots v_{N-1}}
M_{v_0, v_1, \cdots v_{N-1}}^{v'_0, v'_1, \cdots v'_{N-1}}
T^{\dag {s'_{X,0}, s'_{X,1}, \cdots}}_{v'_0, v'_1, \cdots v'_{N-1}} , 
\end{equation}
其中， $s_{X,i}$ 为区域X中各个物理指标， $v_i$ 为区域X和外部相连的边的指标。
公式 [[eqref:eq:PEPS中计算约化密度矩阵]] 中间有一个 $D^N$ 维度的矩阵$M$，其中 $D$ 是PEPS中虚拟边的维度。
而 $S = \ln D^N = N \ln D \propto |\partial X|$ ，所以PEPS可以满足二维系统的纠缠熵面积定律。

*** 投影纠缠对

使用一张张量网络表示波函数时，我们可以有两种阐述方式。第一种是数学上的分解，即对于任意一个 $R$ 个粒子的系统，波函数
\begin{equation}
|\Psi\rangle = T_{i_{T,0}, i_{T,1}, \cdots, i_{T,R-1}} |i_0 i_1 \cdots i_{R-1} \rangle ,
\end{equation}
中 $T$ 作为一个 $R$ 阶张量，可以被分解为一张张量网络：
\begin{equation}
\begin{aligned}
T_{i_{T,0}, i_{T,1}, \cdots, i_{T, R-1}} = &
\prod_{n=0}^{N-1} (A_n)_{i_{A_n, 0} i_{A_n, 1} \cdots i_{A_n, \mathrm{rank}(A_n) -1}}
\\ &
\prod_{b=0}^{B-1} \delta^{i_{A_{V_b^0},E_b^0}}_{i_{A_{V_b^1},E_b^1}}
\\ &
\prod_{r=0}^{R-1} \delta^{i_{T,r}}_{i_{A_{V'_r},E'_r}} .
\end{aligned}
\end{equation}
这张张量网络中有 $N$ 个张量，即 $A_n$ ，其中 $n = 0, 1, \cdots N-1$ 。
张量 $A_n$ 的阶数是 $\mathrm{rank}(A_n)$ ，它的指标被记作 $i_{A_n, j}$ ，其中 $j = 0, 1, \cdots \mathrm{rank}(A_n) - 1$ 。
这张张量网络内部有 $B$ 个边连接两个张量，第 $b$ 个边所连接的是第 $V_b^0$ 个张量的第 $E_b^0$ 个边和第 $V_b^1$ 个张量的第 $E_b^1$ 个边，其中 $b=0,1,\cdots B-1$
而这些张量中，有 $R$ 个边没有被收缩，而是作为物理边出现在张量 $T$ 中，
张量 $T$ 的第 $r$ 个边在张量网络中是第 $V'_r$ 个张量的第 $E'_r$ 个边，其中 $r = 0, 1, \cdots R-1$ 。
这张张量网络中，由 $A_n$ ， $n=0, \cdots N-1$ 组成，由 $V_b^0, V_b^1, V'_r, E_b^0, E_b^1, E'_r$ ， $b=0,\cdots B-1, r=0,\cdots R-1$ 表示张量的图结构。
通过不同的张量网络图结构，可以构造出不同类型的张量网络。

另一种阐述方式是将张量网络态视为对一群纠缠对所构成的母态的投影。
先把波函数写成产生算符的形式：
\begin{equation}\label{eq:一般的波函数}
|\Psi\rangle = T_{i_{T,0}, i_{T,1}, \cdots, i_{T,R-1}} \prod_{r=0}^{R-1} c_r^{\dag i_{T,r}} |\Omega\rangle ,
\end{equation}
其中 $|\Omega\rangle$ 是真空态，  $c_r^{\dag i_{T,r}}$ 是第 $r$ 个粒子处，产生第 $i_{T,r}$ 个构型的算符。
需要注意的是，对于一些系统， $c_r^{\dag i_{T,r}}$ 不一定是单个粒子的产生算符，而可能是多个粒子产生算符的复合。
然后将波函数视为对一个母态的投影：
\begin{equation}
|\Psi\rangle = P M |\Omega\rangle ,
\end{equation}
其中 $P$ 为投影算符， $M$ 为制备母态的算符。
而母态为众多组纠缠对的组合：
\begin{equation}
M = 
\prod_{b=0}^{B-1} a_{b,0}^{\dag d_b} a_{b,1}^{\dag d_b}
,
\end{equation}
其中第 $b$ 组纠缠对由 $a_{b,0}^{\dag d_b}$ 和 $a_{b,1}^{\dag d_b}$ 生成， 这里 $d_b$ 取值范围为 $0, 1, \cdots D_b - 1$ ，其中 $D_b$ 为这组纠缠对的个数。
而投影算符被定义为：
\begin{equation}
\begin{aligned}
P = 
\prod_{n=0}^{N-1} & (A_n)_{i_{A_n, 0} i_{A_n, 1} \cdots i_{A_n, \mathrm{rank}(A_n) -1}} \\
&
\prod_{j=0}^{\mathrm{rank}(A_n) - 1} \left\{
\begin{aligned}
&a^{i_{A_n, j}}_{X_{A_n,j},Y_{A_n, j}} \ & \text{如果 $A_n$ 的第 $j$ 个边为虚拟边}, \\
&c^{\dag i_{A_n,j}}_{Z_{A_n,j}} \ & \text{如果 $A_n$ 的第 $j$ 个边为物理边},
\end{aligned}
\right.
\end{aligned}
\end{equation}
其中 $A_n$ 的第 $j$ 个边，如果是物理边，则是 $|\Psi\rangle$ 的第 $Z_{A_n,j}$ 个边，
如果是虚拟边，则将湮灭掉第 $X_{A_n,j}$ 组纠缠对中粒子，而 $Y_{A_n,j}$ 取 $0$ 或 $1$ ，标记其湮灭的是纠缠对中靠前的还是靠后的粒子。
这种解释方式中，将张量网络的虚拟边用纠缠对表示，投影算子中湮灭同一个纠缠对的两个部分是彼此相连的张量。
每个张量通过湮灭掉纠缠对并产生物理的粒子，实现了将多组纠缠对投影到物理空间的操作，这便是投影纠缠对态的名称由来。
值得注意的是，虽然对纠缠对的投影可以阐述任意图结构的张量网络，但是我们提到“投影纠缠对态”时，都是特指方格形的张量网络的。

在张量网络态的投影纠缠对阐述中，投影部分既有湮灭算符也有产生算符，这不够好看。
我们可以再引入一个虚拟的粒子，得到：
\begin{equation}\label{eq:投影纠缠对阐述的一般张量网络}
\left\{
\begin{aligned}
P &= 
\prod_{n=0}^{N-1} (A_n)_{i_{A_n, 0} i_{A_n, 1} \cdots i_{A_n, \mathrm{rank}(A_n) -1}}
\prod_{j=0}^{\mathrm{rank}(A_n) - 1} 
a^{i_{A_n, j}}_{X_{A_n,j},Y_{A_n, j}} , \\
M &=
\prod_{b=0}^{B-1} a_{b,0}^{\dag d_b} a_{b,1}^{\dag d_b}
\prod_{r=0}^{R-1} a_{r+B,0}^{\dag d_{r+B}} c_r^{\dag d_{r+B}} ,
\end{aligned}
\right.
\end{equation}
这样我们依然可以将公式 [[eqref:eq:一般的波函数]] 表示为母态上的投影，即 $|\Psi\rangle = P M |\Omega\rangle$ 。
这种变型的投影纠缠对阐述将每个张量中各个边平等地对待，图结构的信息完全放置在母态生成算符 $M$ 中。

** 对称性张量和费米子张量

*** 对称性张量 <<sec:::对称性张量>>

当一个系统的哈密顿量拥有某个对称性时，其基态要么满足这个对称性，要么自发破缺从而是简并的。
对称性变换使用一个紧致群 $G$ 来描述，
如果公式 [[eqref:eq:一般的波函数]] 表示的基态波函数满足这个对称性，我们有
\begin{equation}\label{eq:对称性张量}
U_g^{\otimes R} T_{i_{T,0},\cdots, i_{T,R-1}} = T_{i_{T,0},\cdots, i_{T,R-1}} ,
\end{equation}
其中 $g \in G$ ，
$U_g^{\otimes R} = \bigotimes_{r=0}^{R-1} U_g^r$ ， $U_g^r$ 为 $g$ 在张量的第 $r$ 个指标的线性空间上的表示。
满足公式 [[eqref:eq:对称性张量]] 的张量被称作对称性张量 [[cite:Singh2010]] ，图 [[ref:fig:对称性张量和对称性张量网络]] (a)使用图形标记法展示了此关系。
需要注意对称性张量和对称矩阵完全不同，对称矩阵是做交换两个指标的转置变换下不变的矩阵，对称性张量是在每个指标中各自做相同的群元素代表的群变换下不变的张量。

#+begin_export latex
\begin{figure}
\centering
\input{tikz/symmetry.tikz}
\caption{对称性张量和对称性张量网络}
\label{fig:对称性张量和对称性张量网络}
\note{注：
(a)中，对张量做一个对称性变换相当与在张量的每个指标上作用上这个指标上 $g$ 的群表示矩阵，因为是群是紧致的，我们可以给张量找到一组合适的基使得矩阵是酉的。
(b)中，如果张量网络中的每个张量都是对称性张量，我们可以在每个张量的周围都加上群的变换矩阵，而不改变张量网络的值，得到等式的左侧；
而两个张量彼此相互收缩的线性空间是相互共轭的，所以他们的群表示是互逆的，所有的虚拟边上的两个矩阵可以相互抵消而不改变张量网络的值，得到等式的右侧；
所以原有的张量网络等于只在物理边上做群变换，即整个张量网络的收缩结果是对称性张量。}
\end{figure}
#+end_export

从图 [[ref:fig:对称性张量和对称性张量网络]] (b) 中可以很明显看出，对称性张量收缩结果仍然是对称性张量。
所以对于一个已知满足某个对称性的波函数，使用张量网络表示时，可以使用限制更强的拟设：张量网络态中每个张量都是对称性张量。
波函数的物理指标有明确的物理意义，所以给定对称群的群表示是固定的。
而对于一个张量网络态，我们可以将每个虚拟指标所在的线性空间也看作对称群的一个表示空间，
从而我们可以对张量网络态中的每个张量各自做对称性变换，这样每个张量都可以被设置为对称性张量。
值得注意的是，这种虚拟指标所在空间的群表示是任意的。

一个对称性张量的每个边所在的空间都是群的表示空间，空间 $V$ 可以分解为
\begin{equation}
V \cong \bigoplus_{s} d_s V^{s} \cong \bigoplus_{s} (D^{s} \otimes V^{s}),
\end{equation}
其中 $V^s$ 是群的第 $s$ 个不可约表示空间， $d_s$ 是他的重数，这里 $D^s$ 是 $d_s$ 维的简并空间。

我们可以使用 $U_g^r$ 来作张量的第 $r$ 个指标的基，每个指标的空间 $V^r = \bigoplus_s (D^{r,s} \otimes V^s)$ 中，使用 $(s,\alpha_s, m_s)$ 来作为基底。
其中 $s$ 标记了不同的不可约表示， $\alpha_s$ 是简并空间的指标，即 $\alpha_s = 0,1,\cdots d_s-1$ ，而 $m_s$ 是这个不可约表示空间中的指标。

在这个基下，一个张量是一个对称性张量的条件是
+ 0阶 :: 标量显然是一个对称性张量。
+ 1阶 :: 其非零元素只能位于平凡的不可约表示中，即 $s=0$ ，而 $m_0=0$ 。
+ 2阶 :: 其非零元素的两个指标需要在相同的不可约表示空间中，且两者的 $m_s$ 相反，即张量需要满足形式
\begin{equation}
T_{(s_0,\alpha_{s_0},m_{s_0}),(s_1,\alpha_{s_1},m_{s_1})} =
P_{(s_0,\alpha_{s_0}),(s_1,\alpha_{s_1})} \delta_{s_0,s_1}
\begin{pmatrix} s_0 \\ m_{s_0} \quad m_{s_1} \end{pmatrix},
\end{equation}
其中括号是Wigner 1-jm符号。
+ 3阶 :: 张量需要满足形式
\begin{equation}
T_{(s_0,\alpha_{s_0},m_{s_0}),(s_1,\alpha_{s_1},m_{s_1}),(s_2,\alpha_{s_2},m_{s_2})} =
P_{(s_0, \alpha_{s_0}),(s_1, \alpha_{s_1}),(s_2, \alpha_{s_2})}
\begin{pmatrix}
s_0 & s_1 & s_2 \\
m_0 & m_1 & m_2
\end{pmatrix},
\end{equation}
其中括号是Wigner 3-jm符号。
+ 更高阶 :: 张量需要可以被分解为多个3阶对称性张量收缩的形式。

如上所示，一般对称群的对称性张量结构十分复杂，但对于Abel群来说，情况却十分简单。
Abel群的不可约表示一定是1维的，所以恒有 $m_s=0$ ,故我们将 $m_s$ 省略，使用 $(s,\alpha_s)$ 作为基。
此时 $R$ 阶的对称性张量需要满足
\begin{equation}
U_g^{\otimes R} T_{(s_0,\alpha_{s_0}),(s_1,\alpha_{s_1}),\cdots (s_{R-1},\alpha_{s_{R-1}})} =
T_{(s_0,\alpha_{s_0}),(s_1,\alpha_{s_1}),\cdots (s_{R-1},\alpha_{s_{R-1}})},
\end{equation}
而 $U_g^{\otimes R}$ 中每个项目 $U_g^r = U_g^{s_r}$ ，作为一个一维的酉矩阵，就是一个复数。
所以我们得到：
\begin{equation}
T_{(s_0,\alpha_{s_0}),(s_1,\alpha_{s_1}),\cdots (s_{R-1},\alpha_{s_{R-1}})}
\prod_r^{R-1}U_g^{s_r}
=
T_{(s_0,\alpha_{s_0}),(s_1,\alpha_{s_1}),\cdots (s_{R-1},\alpha_{s_{R-1}})}.
\end{equation}
为此，张量需要满足形式：
\begin{equation}\label{eq:Abel对称张量的原始形式}
T_{(s_0,\alpha_{s_0}),(s_1,\alpha_{s_1}),\cdots (s_{R-1},\alpha_{s_{R-1}})} =
P_{(s_0, \alpha_{s_0}),(s_1, \alpha_{s_1}),\cdots (s_{R-1}, \alpha_{s_{R-1}})}
C(s_0,s_1,\cdots s_{R-1}) ,
\end{equation}
其中
\begin{equation}
C(s_0, s_1, \cdots s_{R-1}) = \left\{\begin{aligned}
1 \quad & \text{如果对于任意$g$有}  \quad \prod_{r=0}^{R-1} U_g^{s_r} = 1 ,\\
0 \quad & \text{其他情况},
\end{aligned}\right.
\end{equation}
是对称群决定的对称性条件。
将公式 [[eqref:eq:Abel对称张量的原始形式]] 稍作变形得到：
\begin{equation}
T_{(s_0,\alpha_{s_0}),(s_1,\alpha_{s_1}),\cdots (s_{R-1},\alpha_{s_{R-1}})} =
\left(P_{s_0,s_1,\cdots,s_{R-1}}\right)_{\alpha_{s_0},\alpha_{s_1},\cdots \alpha_{s_{R-1}}}
R(s_0,s_1,\cdots s_{R-1}) .
\end{equation}
可见Abel群的对称性张量是一个分块的张量，其中分块方案由对称性条件和张量每个边上的不可约表示分解决定。

物理中常见的群是 $Z(2)$ 群和 $U(1)$ 群。
对于 $Z(2)$ 群， $g=e$ 表示不变， $g=z$ 表示反转。
群表示 $0$ 中 $U_e^0 = U_z^0 = +1$ ，另一个群表示 $1$ 中 $U_e^1 = +1$ ， $U_z^1 = -1$ 。
所以 $Z(2)$ 群的对称性条件是：
\begin{equation}\label{eq:Z2对称性条件}
C(s_0, s_1, \cdots s_{R-1}) = \left\{\begin{aligned}
1 \quad & \text{如果}  \quad \bigoplus_{r=0}^{R-1} s_r = 0 ,\\
0 \quad & \text{如果}  \quad \bigoplus_{r=0}^{R-1} s_r = 1 ,
\end{aligned}\right.
\end{equation}
其中 $\bigoplus$ 为异或运算。

而对于 $U(1)$ 群， $g=\theta$ 表示旋转 $\theta$ 。
群表示使用一个整数 $s$ 来标记， $U_\theta^s = \mathrm{e}^{\mathrm{i} s \theta}$ 。
所以 $U(1)$ 群的对称性条件是：
\begin{equation}
C(s_0, s_1, \cdots s_{R-1}) = \left\{\begin{aligned}
1 \quad & \text{如果}  \quad \sum_{r=0}^{R-1} s_r = 0 ,\\
0 \quad & \text{如果}  \quad \sum_{r=0}^{R-1} s_r \neq 0 .
\end{aligned}\right.
\end{equation}

对于 $U(1)$ 群和 $Z(2)$ 的乘积群，可以使用各个子群的群表示的乘积来表示这个群的群表示。
比如对于 $U(1) \times Z(2)$ 群，群元素为 $g=(\theta, p)$ ，其中 $p=e=+1$ 表示不变， $p=z=-1$ 表示反转。
群表示可以标记为 $s=(z, b)$ 其中 $z$ 为整数， $b=0$ 或 $1$ ，而 $U_{\theta,p}^{z, b} = \mathrm{e}^{\mathrm{i} z \theta} p^b$ 。
对称性条件 $C=1$ 的条件为
\begin{equation}
\begin{aligned}
1 &= \prod_{r=0}^{R-1} U_{\theta,p}^{z_r, b_r} \\
&= \prod_{r=0}^{R-1} \mathrm{e}^{\mathrm{i} z_r \theta} p^{b_r} \\
&= \mathrm{e}^{\mathrm{i} \sum_{r=0}^{R-1} z_r \theta} p^{\sum b_r} \quad \forall \theta, p ,
\end{aligned}
\end{equation}
即 $\sum_{r=0}^{R-1} z_r = 0$ 且 $\bigoplus_{r=0}^{R-1} b_r = 0$ 。
故而有
\begin{equation}
\begin{aligned}
&C_{U(1)\times Z(2)} ( (z_0, b_0), (z_1, b_1), \cdots (z_{R-1}, b_{R-1}) ) \\
= &C_{U(1)} (z_0, z_1, \cdots z_{R-1}) C_{Z(2)} (b_0, b_1, \cdots b_{R-1}),
\end{aligned}
\end{equation}
可见对于乘积群，对称性张量非零的条件是满足所有子群的对称性条件：对称性条件为各个子群的对称性条件的乘积：
\begin{equation}
C_{\prod_i G_i} = \prod_i C_{G_i} .
\end{equation}

综上所述，Abel群的对称性张量是一个由对称性条件决定的分块张量，由对称性张量所构成的张量网络整体依然满足这个对称性。
对于已知满足某个对称性的波函数来说，使用对称性张量所构成的张量网络来表示能够很好的减少网络参数。

*** 费米子张量

费米子系统中，由于反对易的性质，大部分用于表示费米子系统波函数的方法需要进行Jordan-Wigner变换，即：
\begin{equation}\label{eq:Jordan-Wigner变换}
\left\{
\begin{aligned}
f_i^\dag &= \mathrm{e} ^{+\mathrm{i} \pi \sum_{j=0}^{i-1} a_j^\dag a_j}  a_i^\dag \\
f_i &= \mathrm{e} ^{-\mathrm{i} \pi \sum_{j=0}^{i-1} a_j^\dag a_j}  a_i .
\end{aligned}
\right.
\end{equation}
其中 $a_i^\dag$ 和 $a_i$ 为硬核波色子的产生湮灭算符，或者说是自旋的上升下降算符。
通过此变换，构造出来的 $f_i^\dag$ 和 $f_i$ 拥有费米子的反对易性质。
这意味这，我们可以将费米子系统的哈密顿量中所有的粒子算符，使用公式 [[eqref:eq:Jordan-Wigner变换]] 进行替换，从而得到了一个非波色子的系统。

Jordan-Wigner变换要求给所有的费米子模式排列成一维序列，并让所有的产生湮灭算符添加一个包含序列前面所有粒子粒子数的相位表达式。
对于一维的近临相互作用来说，这种情况不会有太大问题，因为相位表达式中大部分项目都会相互抵消，
比如：
\begin{equation}
\begin{aligned}
f_{i+1}^\dag f_i
&= \mathrm{e}^{+\mathrm{i}\pi \sum_{j=0}^{i} a_j^\dag a_j} a_{i+1}^\dag \mathrm{e}^{-\mathrm{i} \pi \sum_{j=0}^{i-1} a_j^\dag a_j} a_i \\
&= \mathrm{e}^{+\mathrm{i}\pi a_i^\dag a_i} a_{i+1}^\dag a_i ,
\end{aligned}
\end{equation}
可见一维情况的近临相互作用经过Jordan-Wigner变换后依然是近临相互作用。

但是对于二维系统来说，将所有物理边排列成一行后，原本行间的近临相互作用变成了长程的相互作用，如：
\begin{equation}
f_{i+1,j}^\dag f_{i,j} = \mathrm{e} ^ {+\mathrm{i}\pi (\sum_{k=j}^{L_2-1} a_{i,k}^\dag a_{i,k} + \sum_{k=0}^{j-1} a_{i+1,k}^\dag a_{i+1,k})} a_{i+1,j}^\dag a_{i,j} .
\end{equation}
所以即使只有近临相互作用的二维系统，进行Jordan-Wigner变换时，也会引入大量的交换费米子产生的相位符号，并且这是多体且长程的。
当应用Jordan-Wigner变换于张量网络态时，这种长程相互作用，会极大地削弱张量网络态的表示能力。

一种针对费米子的张量网络态可以解决这个问题。
考虑公式 [[eqref:eq:投影纠缠对阐述的一般张量网络]] ，这种张量网络态的阐述中，
使用母态中的纠缠对建立关联，并使用投影算子将母态投影到真实的物理空间中。
如果直接将母态中的物理产生算符替换成真实的费米子产生算符，会破坏原本的网络中，
各个张量和各个边所表示的收缩运算可以随意交换次序的性质。
我们但是我们可以退而求其次，假设包含物理粒子的物理纠缠对，即表示物理边的每组纠缠对
\begin{equation}
P_{\text{物理}, r} = a_{r+B,0}^{\dag d_{r+B}} c_r^{\dag d_{r+B}} ,
\end{equation}
整体呈现没有费米子的性质。
即设 $a_{r+B}^{\dag d_{r+B}}$ 和 $c_r^{\dag d_{r+B}}$ 对于不同的 $d_{r+B}$ 始终拥有相同的费米子奇偶性。
这样的话，母态中产生物理粒子的部分，即张量网络中的物理边，整体是一个波色的算符，可以随意交换顺序。
类似的，对于每组虚拟纠缠对
\begin{equation}
P_{\text{虚拟}, b} = a_{b,0}^{\dag d_b} a_{b,1}^{\dag d_b} ,
\end{equation}
我们也可以将其中的某些替换成费米子的纠缠对，这样依然可以保持这些纠缠对整体的波色性质。
然而，当我们将物理纠缠对和虚拟纠缠对中一部分粒子替换为费米子后，
投影算符中的湮灭算符也对应地变成了费米子，
整体并不能再随意交换了。

考虑到凝聚态物理中，大部分系统的费米子数目是守恒的，即系统至少满足 $U(1)$ 对称性。
我们可以将这个条件先弱化为 $Z(2)$ 对称性，按照 [[ref:sec:::对称性张量]] 中的结论，
我们可以使用 $Z(2)$ 对称性张量来构成表示这个系统的张量网络态。
此时，每个张量网络中的每个张量都是在 $Z(2)$ 对称性变化下不变的分块张量，
公式 [[eqref:eq:投影纠缠对阐述的一般张量网络]] 中投影算符可以写为：
\begin{equation}
\begin{aligned}
P_{\text{投影}, n} =
&(A_{n, (s_0, s_1, \cdots s_{R-1})})_{\alpha_{s_0}, \alpha_{s_1}, \cdots \alpha_{s_{R-1}}} \\
&C(s_0, s_1, \cdots s_{R-1}) \\
&\prod_{j=0}^{\mathrm{rank}(A_n) - 1} 
a^{(s_j, \alpha_{s_j})}_{X_{A_n,j},Y_{A_n, j}} ,
\end{aligned}
\end{equation}
由于只涉及到单个张量，这里为了便利省略了指标中表示张量所有的标记，即将 $s_{A_n,j}$ 写成了 $s_{j}$ 。

这里的 $C(s_0, s_1,\cdots s_{R-1})$ 为公式 [[eqref:eq:Z2对称性条件]] 所描述的 $Z(2)$ 群的对称性条件。
容易验证，当 $C(s_0, s_1, \cdots s_{R-1}) \neq 0$ 时，湮灭算子部分
\begin{equation}
\prod_{j=0}^{\mathrm{rank}(A_n) - 1} 
a^{(s_j, \alpha_{s_j})}_{X_{A_n,j},Y_{A_n, j}}
\end{equation}
一定是波色的。
这保证了投影算子的每个非零项都是波色的，所以投影算子整体是波色的，
从而我们可以对正常的张量一样，随意交换投影算子。

由此可见，我们可以使用 $Z(2)$ 对称性的张量加上含有费米子的纠缠对湮灭算符，
作为费米子张量来构造用于描述费米子系统的张量网络。
这种情况下，我们必须使用纠缠对阐述来理解张量网络态，因为我们需要在母态中包含含有费米子的纠缠对产生算符。

对于费米子张量来说，我们也可以使用更强的 $U(1)$ 对称性，因为更强的对称性对分块有着更强的限制，
对称性条件依然能保证有费米子性质的元素一定为零。
而为了确保费米子张量的可交换性质，一定存在某个对称性。为了区分，我们将这种对称性前面加上词缀 `fermi-' ，
如 fermi-$U(1)$ 对称性 或者 fermi-$Z(2)$ 对称性。
而纠缠对中体现对称性的粒子不是费米子时，我们在对称性前面加上词缀 `bose-' ，如
bose-$U(1)$ 对称性或者bose-$Z(2)$ 对称性。
同样，我们可以将这些对称群进行乘积，比如 fermi-$U(1) \times$ bose-$U(1)$ 对称性，
其可以同时描述电子数和z方向自旋的守恒。

综上所述，费米子张量由某个群的对称性张量和含有费米子的纠缠对构成。
对称性张量即分块的张量，他的每个边上的每个维度都有一个对称群表示的属性，这些属性共同确定了张量分块的方案。
而一组纠缠对的性质中，每个纠缠对是否是费米的性质可以完全由张量边上的对称群表示确定，
但是每个张量边上的湮灭算子到底湮灭的是纠缠对中靠前的那个粒子还是靠后的那个粒子是不确定的。
为此，我们需要给每个边额外加上一个属性，标记这个边对应的产生算符处于纠缠对中的哪一个。
本论文中，使用一个名为费米箭头的布尔数标记纠缠对中的先后顺序：0表示在纠缠对中靠前，1表示在纠缠对中靠后。
当两个张量的边相连时，两个张量的边湮灭的是纠缠对中的两个粒子，必然一个靠前一个靠后，
所以彼此相连的两个边上的费米箭头必然一个为0一个为1。

** 费米子张量上的张量操作

费米子张量中，
对称性张量的各种张量操作过程中与寻常的张量没有差别，
而纠缠对中引入费米子却会改变几乎所有的张量操作，
现在我们需要对各种张量运算一个一个考虑费米子的影响。

*** 张量转置

张量转置是寻常张量中特别普遍的操作。寻常的张量转置仅仅是数据的重新排列，
但是对于费米子张量，边的顺序关系到了湮灭算符的顺序：
交换湮灭算符时，会产生符号。

考虑投影子
\begin{equation}
P_n = 
(A_n)_{i_{0} i_{1} \cdots}
a_0^{i_0} a_1^{i_1} \cdots ,
\end{equation}
交换相邻的两个湮灭算符，如第 $j$ 和第 $j+1$ 个湮灭算符时，如果 $p(a_j^{i_j}) p(a_{j+1}^{i_{j+1}}) = 1$ 则会产生符号，
如果为 $0$ 则不会产生符号，
其中
\begin{equation}
p (a) = \left\{\begin{aligned}
1  \quad & \text{如果} a \text{是费米的} \\
0  \quad & \text{如果} a \text{是波色的} .
\end{aligned}\right.
\end{equation}
为了简单表述，我们称呼这时产生了 $p(a_j^{i_j}) p(a_{j+1}^{i_{j+1}})$ 个符号。

注意到费米子张量是分块的张量，每个分块上的边上有着相同的对称群表示，所以他们湮灭算符的费米子奇偶性也是一样的，
故张量转置时，每个分块产生的符号数是一样的，这为具体实现提供了很大的便利，
因为我们可以一个分块一个分块地分析符号，而不必每个元素单独分析一遍。

当进行更加复杂的转置时，可以分解为多个近临的湮灭算符交换，容易验证：
\begin{equation}
\begin{aligned}
P_n &= 
(A_n)_{i_{0} i_{1} \cdots}
a_0^{i_0} a_1^{i_1} \cdots \\
&= (A'_n)_{i_{s_0} i_{s_1} \cdots} a_{s_0}^{i_{s_0}} a_{s_1}^{i_{s_1}} \cdots ,
\end{aligned}
\end{equation}
其中 $s_0, s_1, \cdots$ 为一个排列，描述了如何转置，而 $A'_n$ 满足：
\begin{equation}
(A'_n)_{i_{s_0} i_{s_1}\cdots} = (A_n)_{i_0 i_1 \cdots} (-1)^{\sum_{j<k,s_j>s_k} p(a_j^{i_j}) p(a_k^{i_k})} .
\end{equation}

*** 张量的共轭

共轭用于将波函数从希尔伯特空间转换到对偶空间，从而进行内积运算。
寻常的张量网络所表示的态进行共轭可以表示为每个张量都取共轭后所组成的张量网络。
对于费米子张量网络，依然有类似的性质。

考虑波函数 $P M | \Omega\rangle$ ，其中 $P$ 和 $M$ 为公式 [[eqref:eq:投影纠缠对阐述的一般张量网络]] 所展示，
求共轭得到 $\langle \Omega | M^\dag P^\dag$ ，其中
\begin{equation}
\left\{
\begin{aligned}
M^\dag &=
\prod_{b=0}^{B-1} a_{b,1}^{d_b} a_{b,0}^{d_b}
\prod_{r=0}^{R-1} c_r^{d_{r+B}} a_{r+B,0}^{d_{r+B}} , \\
P^\dag &= 
\prod_{n=0}^{N-1} (A_n)^\dag_{i_{A_n, 0} i_{A_n, 1} \cdots i_{A_n, \mathrm{rank}(A_n) -1}}
\prod_{j=\mathrm{rank}(A_n) - 1}^{0}
a^{\dag i_{A_n, j}}_{X_{A_n,j},Y_{A_n, j}} . \\
\end{aligned}
\right.
\end{equation}
这里 $P^\dag$ 可以先恢复所有的产生算符的顺序得到
\begin{equation}
P^\dag = 
\prod_{n=0}^{N-1} (-1)^{\sum_{j<k} p(a_j^{i_j}) p(a_k^{i_k})}
(A_n)^\dag_{i_{A_n, 0} i_{A_n, 1} \cdots i_{A_n, \mathrm{rank}(A_n) -1}}
\prod_{j=0}^{\mathrm{rank}(A_n) - 1}
a^{\dag i_{A_n, j}}_{X_{A_n,j},Y_{A_n, j}} . \\
\end{equation}
然而现在，无论是纠缠对的母态 $M^\dag$ 还是投影子中的产生算符，都不符合费米子张量的形式，下面我们一步步地恢复原本的形式。

当计算某个物理量时，真正计算的是
\begin{equation}
\langle \Psi^\dag_1 |O| \Psi_2 \rangle = \langle \Omega | P^\dag_1 M^\dag_1 O M_2 P_2 | \Omega \rangle ,
\end{equation}
考虑其中某组虚拟粒子所在的子空间，表达式为
\begin{equation}
\langle \Omega | a^{d_1} a^{\dag d_2} a^{d_3} a^{\dag d_4} | \Omega \rangle  ,
\end{equation}
其中 $a^{d_1}$ ， $a^{d_2}$ ， $a^{d_3}$ ， $a^{d_4}$ 分别是  $P^\dag_1$ ， $M^\dag_1$ ， $M_2$ ， $P_2$ 中这组粒子的算符，
注意这些算符中的上标 $d_i$ 指的是不同的粒子。
我们可以将共轭空间中的虚拟粒子替换成新的虚拟粒子，其结果依然不变，得到
\begin{equation}
\langle \Omega | a^{d_1} a^{\dag d_2} a^{d_3} a^{\dag d_4} | \Omega \rangle =
\langle \Omega | a'^{d_1} a'^{\dag d_2} a^{d_3} a^{\dag d_4} | \Omega \rangle .
\end{equation}
综上，我们考虑共轭后的张量网络时，可以完全不考虑希尔伯特空间中相同的虚拟粒子的影响。

而对于连接两个张量 $P_x$ 和 $P_y$ 的虚拟边，考虑每个元素，我们可以将湮灭算符对往后面移动：
\begin{equation}
\begin{aligned}
&\overbrace{\left(\cdots (a'_1 a'_0) \cdots\right)}^{M^\dag}
\underbrace{\cdots \overbrace{\left(\cdots a_0^{\prime \dag} \cdots\right)}^{P^\dag_x} \cdots \overbrace{\left(\cdots a_1^{\prime \dag} \cdots\right)}^{P^\dag_y} \cdots}_{P^\dag} \\
= &\left(\cdots\right)\cdots \left(\cdots a'_1 a'_0 a_0^{\prime \dag} \cdots\right) \cdots \left(\cdots a_1^{\prime \dag} \cdots\right)\cdots \\
= &\left(\cdots\right)\cdots \left(\cdots a'_1 \cdots\right) \cdots \left(\cdots a'_0 a_0^{\prime \dag} a_1^{\prime \dag} \cdots\right)\cdots \\
= &\left(\cdots\right)\cdots \left(\cdots a'_1 \cdots\right) \cdots \left(\cdots a'_0 \cdots\right)\cdots (a_0^{\prime \dag} a_1^{\prime \dag}) .
\end{aligned}
\end{equation}
可见所有的虚拟边的共轭，都可以看作正常的费米子张量的费米箭头进行了翻转。

类似的，对于物理边，考虑每一个元素，我们一样可以将 $M^\dag$ 中的算符向后一定：
\begin{equation}
\begin{aligned}
&\overbrace{\left(\cdots (c a') \cdots\right)}^{M^\dag}
\underbrace{\cdots \overbrace{\left(\cdots a'^\dag \cdots\right)}^{P^\dag_n} \cdots}_{P^\dag} \\
= &\left(\cdots\right) \cdots \left(\cdots c a' a'^\dag \cdots\right) \cdots \\
= &\left(\cdots\right) \cdots \left(\cdots a' a'^\dag c \cdots\right) \cdots \\
= &\left(\cdots\right) \cdots \left(\cdots a' \cdots\right) \cdots (a'^\dag c) .
\end{aligned}
\end{equation}
而 $(a'^\dag c)$ 最终将和原空间中的 $(a^\dag c^\dag)$ 组合， 恢复张量网络的求和的形式，相关项目为：
\begin{equation}
\begin{aligned}
\sum_{d'} a'^{\dag {d'}} c^{d'} \sum_d a^{\dag d} c^{\dag d}
&= \sum_{d d'} a^{\dag d} a'^{\dag {d'}} c^{d'} c^{\dag d} \\
&= \sum_{d d'} a^{\dag d} a'^{\dag d'} \delta_{d d'} \\
&= \sum_{d} a^{\dag d} a'^{\dag d} .
\end{aligned}
\end{equation}
这意味这，我们可以简单地认为物理的产生算符在表示整个 $\langle \Psi_1 | O | \Psi_2 \rangle$ 的张量网络中是一个普通的边，
他对应的纠缠对中的产生算副靠前，而类似的，共轭空间中的湮灭算符在纠缠对中靠后。
这样不必再像公式 [[eqref:eq:投影纠缠对阐述的一般张量网络]] 中的 $M$ 那样将物理边和虚拟边分开对待。

综上所述，当我们对一个费米子张量进行共轭时，我们需要
1. 对每个元素取共轭；
2. 加上一个全转置的符号 $(-1)^{\sum_{j<k} p(a_j^{i_j}) p(a_k^{i_k})}$ ；
3. 将所有的费米箭头翻转。

*** 翻转费米箭头

费米箭头用于表示纠缠对中产生算符的顺序，而调换产生算符的顺序常用于其他运算的预处理中。
考虑两个投影子以及母态中的纠缠对产生算符：
\begin{equation}
\begin{aligned}
P M =
&(A_n)_{i_{0} i_{1} \cdots} a_0^{i_0} a_1^{i_1} \cdots \\
&(B_n)_{j_{0} j_{1} \cdots} b_0^{j_0} b_1^{j_1} \cdots \\
& a_x^{\dag d} b_y^{\dag d} ,
\end{aligned}
\end{equation}
其中 $A$ 的第 $x$ 个边与 $B$ 的第 $y$ 个边相连，
交换纠缠对中的两个产生算符得到
\begin{equation}
\begin{aligned}
P M =
&(A_n)_{i_{0} i_{1} \cdots} a_0^{i_0} a_1^{i_1} \cdots \\
&(B_n)_{j_{0} j_{1} \cdots} b_0^{j_0} b_1^{j_1} \cdots \\
& (-1)^{p(a_x^{\dag d}) p(b_y^{\dag d})} b_y^{\dag d} a_x^{\dag d} .
\end{aligned}
\end{equation}
可见当我们翻转两个张量彼此相连的边上的费米箭头时，只产生了一个符号，
不妨将它放置在 $A$ 中，得到：
\begin{equation}
\begin{aligned}
P M =
& (-1)^{p(a_x^{i_x})} (A_n)_{i_{0} i_{1} \cdots} a_0^{i_0} a_1^{i_1} \cdots \\
&(B_n)_{j_{0} j_{1} \cdots} b_0^{j_0} b_1^{j_1} \cdots \\
& b_y^{\dag d} a_x^{\dag d} ,
\end{aligned}
\end{equation}
其中我们用到了
\begin{equation}\label{eq:翻转箭头时的符号推导}
\begin{aligned}
p(a_x^{\dag d}) p(b_y^{\dag d}) &= p(a_x^{\dag d}) ^ 2 \\
&= p(a_x^{\dag d}) \\
&= p(a_x^{i_x}) .
\end{aligned}
\end{equation}
公式 [[eqref:eq:翻转箭头时的符号推导]] 中第一行的等式来自纠缠对中两个粒子拥有相同的费米子奇偶性；
第二行的等式来自对于任意 $a$ ， $p(a)$ 取 $0$ 或者 $1$ ；
第三行的等式来自于整个张量网络中在 $a_x$ 这个粒子的子空间上的分量为
\begin{equation}
\langle \Omega | a^{i_x} a_x^{\dag d} |\Omega\rangle = \delta_{i_x, d} ,
\end{equation}
从而 $i_x \neq d$ 时，张量网络整体都为 $0$ 的事实。

类似的，我们也可以将符号放置在 $B$ 中，从而得到：
\begin{equation}
\begin{aligned}
P M =
& (A_n)_{i_{0} i_{1} \cdots} a_0^{i_0} a_1^{i_1} \cdots \\
& (-1)^{p(b_y^{j_y})}(B_n)_{j_{0} j_{1} \cdots} b_0^{j_0} b_1^{j_1} \cdots \\
& b_y^{\dag d} a_x^{\dag d} .
\end{aligned}
\end{equation}
在实现费米子张量时，我们需要注意在一个网络内翻转费米箭头时，只能会产生一个符号，需要选择放在相连接的两个张量中的哪一个内。
而对于复数张量，我们完全可以产生半个符号即：
\begin{equation}
\begin{aligned}
P M =
& \mathrm{i}^{p(a_x^{i_x})} (A_n)_{i_{0} i_{1} \cdots} a_0^{i_0} a_1^{i_1} \cdots \\
& \mathrm{i}^{p(b_y^{j_y})}(B_n)_{j_{0} j_{1} \cdots} b_0^{j_0} b_1^{j_1} \cdots \\
& b_y^{\dag d} a_x^{\dag d} .
\end{aligned}
\end{equation}

*** 边的合并与拆分

对于寻常张量，边的合并与拆分是很常见的，比如将矩阵视为一个向量，实际上就是将二阶张量的两个边合并为一个边的过程。
对于寻常的稠密张量，边的合并与拆分并不需要真正的数据移动或变换，但是对于对称性张量来说，数据移动是不可避免的。
假设相邻的两个边，其对称群表示分别是 $(s_0^0, s_0^1, \cdots s_0^{d_0-1})$ 和 $(s_1^0, s_1^1, \cdots s_1^{d_1-1})$ ，
其中 $d_0$ 和 $d_1$ 分别是两个边的总维度。
合并成一个边后，群表示为：
\begin{equation}
\begin{aligned}
( &S(s_0^0, s_1^0), S(s_0^0, s_1^1), \cdots S(s_0^0, s_1^{d_1-1}), \\
  &S(s_0^1, s_1^0), S(s_0^1, s_1^1), \cdots S(s_0^1, s_1^{d_1-1}), \\
  &\cdots \\
  &S(s_0^{d_0-1}, s_1^0), S(s_0^{d_0-1}, s_1^{d_0-1}), \cdots S(s_0^{d_0-1}, s_1^{d_1-1})) ,
\end{aligned}
\end{equation}
其中 $S$ 满足：
\begin{equation}
U_g^{s_0} U_g^{s_1} = U_g^{S(s_0, s_1)} , \forall g \in G .
\end{equation}

不难看出，对于 $Z(2)$ 群来说，群表示使用 $0$ 和 $1$ 标记， $S$ 则是布尔异或运算，其构成了表示空间上的 $Z(2)$ 群；
而对于 $U(1)$ 群来说，群表示使用整数标记， $S$ 则是整数加法运算，其构成了表示空间上的 $Z$ 群。
对于更加复杂的Abel群，群表示空间为子群的群表示空间的乘积，
我们可以直接使用子群们的表示空间群的乘积来得到自己的表示空间群，从而得到 $S$ 运算。
当我们得到合并后的边的对称群表示后，我们通常需要再交换各个维度，将相同对称群表示的维度放在一起，从而保证张量的分块数目尽可能地少。

而对于费米子张量，边上的对称群表示需要按照对称性张量的规则做变换外，纠缠对也需要进行变换。
仍然以合并两个相邻的边为例，考虑：
\begin{equation}
\begin{aligned}
P M =
&(A_n)_{i_{0} i_{1} \cdots} \left(\cdots a_x^{i_x} a_{x+1}^{i_{x+1}} \cdots\right)\\
&(B_n)_{j_{0} j_{1} \cdots} \left(\cdots b_y^{j_y} b_{y+1}^{j_{y+1}} \cdots\right) \\
&\left( a_x^{\dag d_0} b_y^{\dag d_0} \right) \left( a_{x+1}^{\dag d_1} b_{y+1}^{\dag d_1} \right) ,
\end{aligned}
\end{equation}
当我们合并边时，纠缠对也需要合并，得到：
\begin{equation}
\begin{aligned}
P M =
&(A_n)_{i_{0} i_{1} \cdots} \left(\cdots a_x^{i_x} a_{x+1}^{i_{x+1}} \cdots\right)\\
&(B_n)_{j_{0} j_{1} \cdots} \left(\cdots b_y^{j_y} b_{y+1}^{j_{y+1}} \cdots\right) \\
&
(-1)^{p(b_y^{d_0}) p(b_{y+1}^{d_1})}
(a_x^{d_0}a_{x+1}^{d_1})^\dag
(b_y^{d_0} b_{y+1}^{d_1})^\dag
.
\end{aligned}
\end{equation}
类似翻转费米箭头的情况，我们可以选择将产生的单个符号放在 $A$ 中或者 $B$ 中：
\begin{equation}
\begin{aligned}
PM=
&
(-1)^{p(a_x^{i_x}) p(a_{x+1}^{i_{x+1}})}
(A_n)_{i_{0} i_{1} \cdots} \left(\cdots a_x^{i_x} a_{x+1}^{i_{x+1}} \cdots\right)\\
&
(B_n)_{j_{0} j_{1} \cdots} \left(\cdots b_y^{j_y} b_{y+1}^{j_{y+1}} \cdots\right) \\
&
(a_x^{d_0}a_{x+1}^{d_1})^\dag
(b_y^{d_0} b_{y+1}^{d_1})^\dag
,
\end{aligned}
\end{equation}
或者
\begin{equation}
\begin{aligned}
PM=
&(A_n)_{i_{0} i_{1} \cdots} \left(\cdots a_x^{i_x} a_{x+1}^{i_{x+1}} \cdots\right)\\
&
(-1)^{p(b_y^{j_y}) p(b_{y+1}^{j_{y+1}})}
(B_n)_{j_{0} j_{1} \cdots} \left(\cdots b_y^{j_y} b_{y+1}^{j_{y+1}} \cdots\right) \\
&
(a_x^{d_0}a_{x+1}^{d_1})^\dag
(b_y^{d_0} b_{y+1}^{d_1})^\dag
.
\end{aligned}
\end{equation}

如果要合并并非相连的两个边，需要进行张量的转置，
而如果要合并费米箭头不一致的两个边，需要先对费米箭头进行翻转。
容易验证，对于合并连续的 $l$ 个边，其产生的符号等于这些合并的边的全转置产生的符号：
\begin{equation}
\begin{aligned}
PM=
&
(-1)^{\sum_{m<n} p(a_m^{i_m}) p(a_n^{i_n})}
(A_n)_{i_{0} i_{1} \cdots} \left(\cdots a_x^{i_x} a_{x+1}^{i_{x+1}} \cdots a_{x+l-1}^{i_{x+l-1}} \cdots\right)\\
&
(B_n)_{j_{0} j_{1} \cdots} \left(\cdots b_y^{j_y} b_{y+1}^{j_{y+1}} \cdots b_{y+l-1}^{j_{y+l-1}} \cdots\right) \\
&
(a_x^{d_0}a_{x+1}^{d_1}\cdots a_{x+l-1}^{d_{l-1}})^\dag
(b_y^{d_0} b_{y+1}^{d_1}\cdots b_{y+l-1}^{d_{l-1}})^\dag
,
\end{aligned}
\end{equation}
或者
\begin{equation}
\begin{aligned}
PM=
&
(A_n)_{i_{0} i_{1} \cdots} \left(\cdots a_x^{i_x} a_{x+1}^{i_{x+1}} \cdots a_{x+l-1}^{i_{x+l-1}} \cdots\right)\\
&
(-1)^{\sum_{m<n} p(b_m^{j_m}) p(b_n^{j_n})}
(B_n)_{j_{0} j_{1} \cdots} \left(\cdots b_y^{j_y} b_{y+1}^{j_{y+1}} \cdots b_{y+l-1}^{j_{y+l-1}} \cdots\right) \\
&
(a_x^{d_0}a_{x+1}^{d_1}\cdots a_{x+l-1}^{d_{l-1}})^\dag
(b_y^{d_0} b_{y+1}^{d_1}\cdots b_{y+l-1}^{d_{l-1}})^\dag
,
\end{aligned}
\end{equation}


值得一提的是，这些产生算符组合而来的复合粒子产生算符依然可以作为张量网络中的纠缠对，因为依然有
\begin{equation}
(b_y^{d'_0} b_{y+1}^{d'_1}\cdots b_{y+l-1}^{d'_{l-1}})
(b_y^{d_0} b_{y+1}^{d_1}\cdots b_{y+l-1}^{d_{l-1}})^\dag
=
\delta_{d_0 d'_0}
\delta_{d_1 d'_1}
\cdots
\delta_{d_{l-1} d'_{l-1}}
\end{equation}

在计算 $\sum_{m<n} p_m p_n$ 原本的两层循环可以使用一个技巧压缩为一层循环：
\begin{equation}
\begin{aligned}
\sum_{m<n} p_m p_n
&= \frac{\sum_{m,n} p_m p_n - \sum_{n} p_n^2}{2} \\
&= \frac{(\sum_{n} p_n)^2 - \sum_{n} p_n}{2} .
\end{aligned}
\end{equation}
由于它出现在 $-1$ 的指数上，我们只关注它的二进制第一位，即只关注$(\sum_{n} p_n)^2 - \sum_{n} p_n$ 的二进制第二位，
而对于任意 $x$ ， $x^2 - x$ 的二进制第二位和 $x$ 的二进制第二位相同，所以
\begin{equation}
(-1)^{\sum_{m<n} p_m p_n}
=
(-1)^{ \frac{2 \& \sum_n{p_n} }{ 2 }} ,
\end{equation}
其中 $\&$ 为按位与。

对于边的拆分，由于它是边的合并的逆运算，其产生的符号和边的合并产生的符号完全一样。

*** 张量的收缩

张量的收缩即将两个相连的张量的公共边的所有维度进行求和。
为了收缩两个费米子张量，我们可以按照合并边、做含有费米子的矩阵乘法，拆分边的思路来实现费米子张量的收缩。
接下来，我们介绍一种具体的方案。

对于两个费米子张量 $A$ 和 $B$ ，它们的边分为两组，即公共边和自由边：公共边连接了彼此，而其他边都是自由边。为了进行收缩，我们依次做：
+ 张量转置：将 $A$ 中所有的自由边放置在左侧，公共边放置在右侧，而 $B$ 中所有的公共边放置在左侧，自由边放置在右侧。
+ 翻转费米箭头：
  将 $A$ 中所有自由边的费米箭头翻转到位置 $0$ ，如果产生符号，则符号不放在本张量中；
  将 $A$ 中所有公共边的费米箭头翻转到位置 $1$ ，如果产生符号，则符号放在本张量中；
  将 $B$ 中所有自由边的费米箭头翻转到位置 $0$ ，如果产生符号，则符号不放在本张量中；
  将 $B$ 中所有公共边的费米箭头翻转到位置 $0$ ，如果产生符号，则符号不放在本张量中。
+ 边的合并：合并 $A$ 和 $B$ 中所有的公共边和自由边， 得到
\begin{equation}
\left\{
\begin{aligned}
P_A &= A_{i_0 i_1} a_0^{i_0} a_1^{i_1} ,\\
P_B &= B_{j_0 j_1} b_0^{j_0} b_1^{j_1} ,\\
M &= b_0^{\dag d} a_1^{\dag d} ,
\end{aligned}
\right.
\end{equation}
  其中，
  $A$ 的自由边合并时如果产生符号，则不放在本张量中；
  $A$ 的公共边合并时如果产生符号，则放在本张量中；
  $B$ 的自由边合并时如果产生符号，则不放在本张量中；
  $B$ 的公共边合并时如果产生符号，则不放在本张量中；
+ 矩阵乘法：直接进行矩阵乘法：
\begin{equation}
\begin{aligned}
P_A P_B M
&=
A_{i_0 i_1}a_0^{i_0} a_1^{i_1}
B_{j_0 j_1}b_0^{j_0} b_1^{j_1}
b_0^{\dag d} a_1^{\dag d} \\
&=
A_{i_0 i_1}
B_{j_0 j_1}
\delta_{j_0 i_1}
a_0^{i_0}
b_1^{j_1}.
\end{aligned}
\end{equation}
+ 边的拆分：拆分剩下的两个自由边，恢复张量原本的形状，产生的符号一律不放在本张量中。
+ 翻转费米箭头：
  将费米箭头翻转到 $A$ 和 $B$ 中原本的位置，产生的符号一律不放在本张量中。

在这个方案中，公共边的合并与费米箭头翻转产生的符号都放且仅放在张量 $A$ 中了。
而对于自由边的合并与第一次费米箭头翻转，完全和自由边的拆分与第二次翻转相互抵消。
由此，我们可以将费米子的张量收缩转换成对称性矩阵的矩阵乘法，即分块的矩阵乘法。

*** 张量的分解

张量的分解即张量变形为矩阵后的矩阵分解，包括QR分解，奇异值分解等。
作为张量收缩的逆操作，我们完全可以讲张量收缩的方案倒过来，作为张量分解的方案，除了最中间的矩阵乘法，替换为矩阵分解。
下面我们介绍一种张量分解的方案。

对于矩阵 $A$ ，我们要将它分解为 $A = B \prod_{k=0}^{K-1} C_k D$ 。
对于奇异值分解，我们有
\begin{equation}
\left\{
\begin{aligned}
B &= U \\
D &= V \\
K &= 1 \\
C_0 &= S.
\end{aligned}
\right.
\end{equation}
对于QR分解，我们有
\begin{equation}
\left\{
\begin{aligned}
B &= Q \\
D &= R \\
K &= 0 .
\end{aligned}
\right.
\end{equation}
对于LQ分解，我们有
\begin{equation}
\left\{
\begin{aligned}
B &= L \\
D &= Q \\
K &= 0 .
\end{aligned}
\right.
\end{equation}
为了进行张量的分解，我们沿着反方向的矩阵收缩过程，依次做：
+ 张量转置：
  将 $A$ 中的各个边调整到合适的位置，即最终出现在 $B$ 中的边放在左侧，而最终出现在 $D$ 中的边放在右侧。
+ 翻转费米箭头：
  讲张量 $A$ 中所有的费米箭头翻转到位置 $0$ ，如果产生了符号，则符号不放置在张量中。
+ 边的合并：
  将 $A$ 中所有最终出现在 $B$ 中的边合并成一个边，而最终出现在 $D$ 中的边合并成另一个边，如果产生了符号，则符号不放置在张量中。
+ 矩阵分解：直接进行矩阵分解：
\begin{equation}
\begin{aligned}
A_{i_0 i_1} a_0^{i_0} a_1^{i_1} =
&\left( B_{i_0 j_1} \prod_{j=0}^{K-1} C_{j_k, j_{k+1}} D_{j_K, i_1} \right) a_0^{i_0} a_1^{i_1}\\
=
&B_{i_0, j_0} a_0^{i_0} b_0^{j_0} \\
&\prod_{k=0}^{K-1} C_{j'_k, j_{k+1}} c_0^{j'_k} b_1^{j_{k+1}} \\
&D_{j'_{K}, i_1} c_K^{j'_K} a_1^{i_1} \\
&\prod_{k=0}^{K} c_k^{\dag d} b_k^{\dag d} .
\end{aligned}
\end{equation}
+ 边的拆分：拆分 $B$ 和 $D$ 中原先在 $A$ 中的边，恢复边原来的形状，如果产生了符号，则符号不放置在张量中。
+ 翻转费米箭头：将 $B$ 和 $D$ 中原先在 $A$ 中的边上的费米箭头翻转到原本的位置，如果产生了符号，则符号不放置在张量中。

类似张量的收缩，这种方法中，边的合并与第一次翻转费米箭头完全和边的拆分与第二次翻转费米箭头相互抵消。
而在矩阵分解的步骤中，在结果中选取合适的费米箭头，可以让计算成直接的分块张量分解，而没有任何其他的费米子性质。

* 张量网络态的优化方法 <<sec:张量网络态的优化方法>>

** 虚时间演化算法

** 采样方法与基于采样方法的变分法

#+begin_export latex
\bibliography{main}
\appendix
#+end_export

#+begin_export latex
\backmatter
#+end_export

#+begin_export latex
\begin{acknowledgements}
在研究学习期间，我有幸得到了三位老师的教导，
他们是：我的导师，中国科大XXX研究员，中科院X昆明动物所马老师以及美国犹他大学的XXX老师。
三位深厚的学术功底，严谨的工作态度和敏锐的科学洞察力使我受益良多。
衷心感谢他们多年来给予我的悉心教导和热情帮助。

感谢XXX老师在实验方面的指导以及教授的帮助。
科大的XXX同学和XXX同学参与了部分试验工作，在此深表谢意。

TODO
\end{acknowledgements}

\begin{publications}

\section*{已发表论文}

\begin{enumerate}
\item A A A A A A A A A
\item A A A A A A A A A
\item A A A A A A A A A
\end{enumerate}

\section*{待发表论文}

\begin{enumerate}
\item A A A A A A A A A
\item A A A A A A A A A
\item A A A A A A A A A
\end{enumerate}

\section*{研究报告}
\begin{enumerate}
\item A A A A A A A A A
\item A A A A A A A A A
\item A A A A A A A A A
\end{enumerate}

TODO
\end{publications}
#+end_export
