#+LATEX_COMPILER: xelatex
#+LATEX_CLASS: thesis
#+OPTIONS: title:nil
#+OPTIONS: toc:nil

#+begin_src emacs-lisp :exports none :results none
  (add-to-list 'org-latex-classes
               '("thesis"
                 "\\documentclass{ustcthesis}\\input{ustcsetup.tex}
                  [NO-DEFAULT-PACKAGES]
                  [NO-PACKAGES]"
                 ("\\chapter{%s}" . "\\chapter*{%s}")
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
#+end_src

#+begin_export latex
\maketitle
\copyrightpage
\frontmatter
#+end_export

#+begin_export latex
\ustcsetup{
  keywords  = {张量网络态，强关联系统，量子多体问题，投影纠缠对态},
  keywords* = {Tensor network state, Strongly correlated systems, Quantum many-body problems, PEPS},
}
#+end_export

#+begin_export latex
\begin{abstract}
摘要 TODO
\end{abstract}

\begin{abstract*}
abstract TODO
\end{abstract*}
#+end_export

#+begin_export latex
\tableofcontents
\listoffigures
\listoftables
#+end_export

* 主要符号对照表

#+begin_export latex
\newenvironment{ustcnotation}{\begin{notation}\begin{notationlist}{2em}}{\end{notationlist}\end{notation}}
#+end_export

#+attr_latex: :environment ustcnotation
- ED :: 严格对角化（Exact Diagonalization）
- QMC :: 量子蒙特卡洛方法 (Quantum Monte Carlo)
- Ansatz :: 拟设（Ansatz）
- TNS :: 张量网络态 (Tensor Network States)
- MPS :: 矩阵乘积态 (Matrix Product States)
- PEPS :: 投影纠缠对态 (Projected Entangled Pair States)
- iTEBD :: 逐块虚时间演化 (Imaginary Time-evolving Block Decimation)
- SU :: 简单更新（Simple Update）

TODO

#+begin_export latex
\mainmatter
#+end_export

* 绪论 <<sec:绪论>>

上世纪发展的郎道费米液体理论和基于自发对称性破缺的相变理论在强关联系统中失效。
在这种系统中，粒子之间的相互作用非常强，使得传统微扰方法难以给出准确结果。
因此，对这类系统的性质分析主要依赖于数值方法。
故发展针对强关联系统的数值方法成了近年来备受关注的研究方向之一。

强关联系统的数值求解受制于巨大的希尔伯特空间维度，其随着系统尺寸增大而呈指数增长。
因此，传统严格对角化(ED)方法仅适用于约30个格点的有限系统求解。
在某些特殊的强关联系统中，量子蒙特卡洛方法(QMC)能够给出优异结果，但有阻错的系统存在符号问题，为了收敛它依然必须指数增加采样量。
另一大类方法则使用拟设(Ansatz)函数来表示波函数，如何用有限数据量表示庞大的希尔伯特空间中的向量是这类数值方法的出发点。

近年来，除了一些传统的有偏拟设和神经网络态拟设，张量网络态(TNS)拟设备受到极大关注。
2003年，Vidal提出了矩阵乘积态作为最早的张量网络态[[cite:Vidal2003]]。
这种方法使用一维张量链来表示一维系统的波函数，特别适合满足纠缠熵面积定律的系统。
Verstaete随后将其推广至二维系统，即投影纠缠对态(PEPS)[[cite:Verstraete2004]]，同样适用于满足面积定律的二维系统。
Vidal针对矩阵乘积态提出了逐块虚时间演化算法(iTEBD)[[cite:Vidal2004,Vidal2007]]，能有效获得一维系统的基态。
然而在处理二维系统时，优化投影纠缠态变得十分困难，逐块虚时间演化算法难以获得精确结果。
2008年，向涛通过在二维系统逐块虚时间演化算法中引入简单环境得到简单更新(SU)方法[[cite:Jiang2008]]，实现在计算效率不减的情况下近似获得基态结果。
获得系统基态后，为计算相关物理量观测值，需要对二维双层张量网络进行收缩。
Sandvik于2007年提出了采样方法[[cite:Sandvik2007]]，通过仅收缩二维单层张量网络，便能计算观测量。
2017年，采样方法被用于计算能量梯度[[cite:Liu2017]]，从而可用采样方法直接优化拟设波函数。
近几年，直接采样方法[[cite:Vieijra2021]]和自然梯度法[[cite:Neuscamman2012]]被引入，极大提升了采样效率和优化效率。

本论文将介绍近些年我们对基于采样的张量网络方法的发展与应用。主要结构安排如下：
+ 第 [[ref:sec:绪论]] 章绪论，即本章。
+ 第 [[ref:sec:张量和张量网络]] 章详细介绍张量和张量网络的理论。
TODO

* 张量和张量网络 <<sec:张量和张量网络>>

** 矩阵乘积态

** 常规张量网络的定义

** 对称性张量和对称性张量网络

** 费米子张量和费米子张量网络

* 张量网络方法与发展

** 虚时间演化算法

** 采样方法与基于采样方法的变分法

#+begin_export latex
\bibliography{main}
\appendix
#+end_export

#+begin_export latex
\backmatter
#+end_export

#+begin_export latex
\begin{acknowledgements}
在研究学习期间，我有幸得到了三位老师的教导，
他们是：我的导师，中国科大XXX研究员，中科院X昆明动物所马老师以及美国犹他大学的XXX老师。
三位深厚的学术功底，严谨的工作态度和敏锐的科学洞察力使我受益良多。
衷心感谢他们多年来给予我的悉心教导和热情帮助。

感谢XXX老师在实验方面的指导以及教授的帮助。
科大的XXX同学和XXX同学参与了部分试验工作，在此深表谢意。

TODO
\end{acknowledgements}

\begin{publications}

\section*{已发表论文}

\begin{enumerate}
\item A A A A A A A A A
\item A A A A A A A A A
\item A A A A A A A A A
\end{enumerate}

\section*{待发表论文}

\begin{enumerate}
\item A A A A A A A A A
\item A A A A A A A A A
\item A A A A A A A A A
\end{enumerate}

\section*{研究报告}
\begin{enumerate}
\item A A A A A A A A A
\item A A A A A A A A A
\item A A A A A A A A A
\end{enumerate}

TODO
\end{publications}
#+end_export
