#+LATEX_CLASS: thesis
#+OPTIONS: title:nil
#+OPTIONS: toc:nil

#+begin_src emacs-lisp :exports none :results none
  (add-to-list 'org-latex-classes
               '("thesis"
                 "\\documentclass{ustcthesis}\\input{ustcsetup.tex}
                  [NO-DEFAULT-PACKAGES]
                  [NO-PACKAGES]"
                 ("\\chapter{%s}" . "\\chapter*{%s}")
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
  (setq org-latex-pdf-process
        '("xelatex -interaction nonstopmode -output-directory %o %f"
          "bibtex %b"
          "xelatex -interaction nonstopmode -output-directory %o %f"
          "xelatex -interaction nonstopmode -output-directory %o %f"))
  (setq org-format-latex-options (plist-put org-format-latex-options :scale 4.0))
#+end_src

#+begin_export latex
\maketitle
\copyrightpage
\frontmatter
#+end_export

#+begin_export latex
\ustcsetup{
  keywords  = {张量网络态，强关联系统，量子多体问题，投影纠缠对态},
  keywords* = {Tensor network state, Strongly correlated systems, Quantum many-body problems, PEPS},
}
#+end_export

#+begin_export latex
\begin{abstract}
摘要 TODO
\end{abstract}

\begin{abstract*}
abstract TODO
\end{abstract*}
#+end_export

#+begin_export latex
\tableofcontents
\listoffigures
\listoftables
#+end_export

* 主要符号对照表

#+begin_export latex
\newenvironment{ustcnotation}{\begin{notation}\begin{notationlist}{2em}}{\end{notationlist}\end{notation}}
#+end_export

#+attr_latex: :environment ustcnotation
- ED :: 严格对角化 (Exact Diagonalization)
- QMC :: 量子蒙特卡洛方法 (Quantum Monte Carlo)
- Ansatz :: 拟设 (Ansatz)
- TNS :: 张量网络态 (Tensor Network States)
- MPS :: 矩阵乘积态 (Matrix Product States)
- PEPS :: 投影纠缠对态 (Projected Entangled Pair States)
- iTEBD :: 逐块虚时间演化 (Imaginary Time-evolving Block Decimation)
- SU :: 简单更新 (Simple Update)
- DMRG :: 密度矩阵重整化 (Density Matrix Renormalization Group)

TODO

#+begin_export latex
\mainmatter
#+end_export

* 绪论 <<sec:绪论>>

上世纪发展的郎道费米液体理论和基于自发对称性破缺的相变理论在强关联系统中失效。
在这种系统中，粒子之间的相互作用非常强，使得传统微扰方法难以给出准确结果。
因此，对这类系统的性质分析主要依赖于数值方法。
故发展针对强关联系统的数值方法成了近年来备受关注的研究方向之一。

强关联系统的数值求解受制于巨大的希尔伯特空间维度，其随着系统尺寸增大而呈指数增长。
因此，传统严格对角化(ED)方法仅适用于约30个格点的有限系统求解。
在某些特殊的强关联系统中，量子蒙特卡洛方法(QMC)能够给出优异结果，但有阻错的系统存在符号问题，为了收敛它依然必须指数增加采样量。
另一大类方法则使用拟设(ansatz)函数来表示波函数，如何用有限数据量表示庞大的希尔伯特空间中的向量是这类数值方法的出发点。

近年来，除了一些传统的有偏拟设和神经网络态拟设，张量网络态(TNS)拟设备受到极大关注。
2003年，Vidal提出了矩阵乘积态作为最早的张量网络态 [[cite:Vidal2003]] 。
这种方法使用一维张量链来表示一维系统的波函数，特别适合满足纠缠熵面积定律的系统。
Verstaete随后将其推广至二维系统，即投影纠缠对态(PEPS) [[cite:Verstraete2004]] ，同样适用于满足面积定律的二维系统。
Vidal针对矩阵乘积态提出了逐块虚时间演化算法(iTEBD) [[cite:Vidal2004,Vidal2007]] ，能有效获得一维系统的基态。
然而在处理二维系统时，优化投影纠缠态变得十分困难，逐块虚时间演化算法难以获得精确结果。
2008年，向涛通过在二维系统逐块虚时间演化算法中引入简单环境得到简单更新(SU)方法 [[cite:Jiang2008]] ，实现在计算效率不减的情况下近似获得基态结果。
获得系统基态后，为计算相关物理量观测值，需要对二维双层张量网络进行收缩。
Sandvik于2007年提出了采样方法 [[cite:Sandvik2007]] ，通过仅收缩二维单层张量网络，便能计算观测量。
2017年，采样方法被用于计算能量梯度 [[cite:Liu2017]] ，从而可用采样方法直接优化拟设波函数。
近几年，直接采样方法 [[cite:Vieijra2021]] 和自然梯度法 [[cite:Neuscamman2012]] 被引入，极大提升了采样效率和优化效率。

本论文将介绍近些年我们对基于采样的张量网络方法的发展与应用。主要结构安排如下：
+ 第 [[ref:sec:绪论]] 章绪论，即本章。
+ 第 [[ref:sec:张量和张量网络]] 章详细介绍张量和张量网络的基础理论。
+ 第 [[ref:sec:张量网络态的优化方法]] 章介绍多种张量网络态的优化方法。

本论文将一直使用爱因斯坦求和约定。本论文将一直从 $0$ 开始计数而不是 $1$ 开始计数。

* 张量和张量网络 <<sec:张量和张量网络>>

** 矩阵乘积态 (MPS)

*** MPS的表示

数值模拟量子多体问题的根本困难在于系统的希尔伯特空间的维度随着系统尺寸的增大指数上升。
比如对于自旋系统，由 $N$ 个自旋 $\frac{1}{2}$ 的粒子构成的格点有 $2^N$ 维的希尔伯特空间，为了表示这个系统的状态，需要 $2^N$ 维的向量作为波函数。
所以不做任何近似的严格表示这个波函数，并精确求解系统的本征态，只能处理很小的系统。
而White在1992年提出了密度矩阵重整化(DMRG)方法 [[cite:White1992]] 成功地求解了各种一维模型的低能态性质。
后来Vidal提出矩阵乘积态(MPS) [[cite:Vidal2003]] ，人们认识到DMRG方法可以被认为是对MPS表示的波函数进行优化的过程。

首先介绍一下张量，它可以被简单地认为是多个线性空间上的多线性映射：
\begin{equation}
\hat T : V_0 \otimes V_1 \otimes V_2 \cdots V_{\mathrm{rank}(T)-1} \to \mathbb{K} .
\end{equation}
其中 $V_r$ 是 $\mathbb{K}$ 上的线性空间， $r=0,1,2,\cdots \mathrm{rank}(T)-1$ 。
而本论文中， $\mathbb{K}$ 只会取 $\mathbb{R}$ 或者 $\mathbb{C}$ ， $V_r$ 也一定是定义了内积的有限维线性空间，
所以可以使用一个高维数组来表示一个张量，即
\begin{equation}
\hat T (
\sum_{i_0=0}^{D_0-1} a_0^{i_0} e_0^{i_0},
\sum_{i_1=0}^{D_1-1} a_1^{i_1} e_1^{i_1},
\cdots
\def\rrr{{R-1}}
\sum_{i_\rrr=0}^{D_{R-1}-1} a_\rrr^{i_\rrr} e_\rrr^{i_\rrr}
)
=
T^{i_0,i_1,\cdots,i_\rrr} a_0^{i_0} a_1^{i_1} \cdots a_\rrr^{i_\rrr},
\end{equation}
其中 $D_r = \mathrm{dim}(V_r)$ ， 而 $R=\mathrm{rank}(T)$ 。
为了表达上的简便，我们直接称呼 $T$ 为张量。

MPS使用一个张量链来表示高维的向量。
以自旋 $\frac{1}{2}$ 系统为例子，一个长度为 $L$ 的自旋系统波函数
\begin{equation}\label{eq:一维系统波函数}
|\Psi\rangle = T^{\sigma_0,\sigma_1,\cdots,\sigma_{L-1}} |\sigma_0 \sigma_1 \cdots \sigma_{L-1}\rangle ,
\end{equation}
可以被使用MPS来表示：
\begin{equation}\label{eq:一维系统波函数的MPS展开}
T^{\sigma_0,\sigma_1,\cdots,\sigma_{L-1}} =
(A_0 ^ {\sigma_0})_{v_1}
(A_1 ^ {\sigma_1})_{v_1 v_2}
(A_2 ^ {\sigma_2})_{v_2 v_3}
\cdots (A_{L-1} ^ {\sigma_{N-1}})_{v_{N-1}} ,
\end{equation}
其中 $\sigma_i$ 为第 $i$ 个格点处的自旋，可以取 $\uparrow$ 或者 $\downarrow$。
从公式 [[eqref:eq:一维系统波函数的MPS展开]] 中看到，MPS表示的波函数在一个构型下的分量，是一连串的矩阵乘积，这是矩阵乘积态(MPS)名称由来。

在MPS表示中，除了最左边和最右边的格点外，第 $i$ 个格点处的 $(A_i^{\sigma_i})_{v_i v_{i+1}}$ 是一个三阶张量，它有一个物理指标 $\sigma_i$
和两个虚拟指标 $v_i$ 和 $v_{i+1}$ 。
其中物理指标 $\sigma_i$ 可以取 $\uparrow$ 或者 $\downarrow$，其维度是 $2$ ，通常使用 $d$ 标记。
而虚拟指标的维度是一个可调节的参数，通常用 $D$ 表示。
这些指标被称作虚拟指标是因为他们并不是真正的物理指标。
对于其他类型的系统，一个格点处的物理维度并不一定是 $2$ ，如tJ模型 $d=3$ ， Hubbard模型 $d=4$ 。

*** 面积定律与MPS

在 $D$ 不变的情况下，MPS可以使用随着系统尺寸线性上升的参数来表示维度指数上升的波函数。
而固定 $D$ 的MPS正合适表示满足纠缠熵面积定律的态。

一个量子态分割成两个部分A和B后，A部分和B部分之间的纠缠熵是
\begin{equation}\label{eq:纠缠熵}
S_{A|B} = - \mathrm{tr} (\hat\rho_A \ln \hat\rho_A) = - \mathrm{tr} (\hat\rho_B \ln \hat\rho_B) = - \sum_{v=0}^{V-1} \lambda_v \ln \lambda_v,
\end{equation}
其中 $\hat\rho_A$ 和 $\hat\rho_B$ 是A部分和B部分的约化密度矩阵，$\lambda_v$ 是他们的本征值， $V$ 为约化密度矩阵的维度。
纠缠熵最大的情况下，所有的本征值相等，即 $\lambda_v = \frac{1}{V}$，此时 $S_{A|B} = \ln V$ 。
而约化密度矩阵的维度随着较小系统的尺寸指数上升，不妨假设A部分比B部分更小， 有$S_{A|B} \propto |A|$ ，其中 $|A|$ 为A部分的体积。
而当系统满足纠缠熵面积定律时，纠缠熵有更强的约束， 即
\begin{equation}\label{eq:面积定律}
S_{A|B} \propto |\partial A| = |\partial B|,
\end{equation}
其中 $|\partial X|$ 表示X的边界大小。

对于公式 [[eqref:eq:一维系统波函数的MPS展开]] 表示的MPS， 切割为长度为 $X$ 和 $Y$ 的两部分， $X+Y=L$ ，X部分的约化密度矩阵为
\begin{equation}\label{eq:MPS切割后的约化密度矩阵}
\begin{aligned}
(\hat\rho_X)_{\sigma_0,\sigma_1,\cdots,\sigma_{X-1}}^{\sigma'_0,\sigma_2,\cdots,\sigma'_{X-1}} =&
(A_0 ^ {\sigma_0})_{v_1}
\cdots
(A_{X-1} ^ {\sigma_{X-1}})_{v_{X-1} v_X}
(A_X ^ {\sigma_X})_{v_X v_{X+1}}
\cdots
(A_{L-1} ^ {\sigma_{N-1}})_{v_{N-1}}
\\
&
(A_0 ^ {\sigma'_0})^\dag_{v'_1}
\cdots
(A_{X-1} ^ {\sigma'_{X-1}})^\dag_{v'_{X-1} v'_X}
(A_X ^ {\sigma_X})^\dag_{v'_X v'_{X+1}}
\cdots
(A_{L-1} ^ {\sigma_{N-1}})^\dag_{v'_{N-1}} .
\end{aligned}
\end{equation}
注意到
\begin{equation}
\begin{aligned}
(\hat\rho_X)_{\sigma_0,\sigma_1,\cdots,\sigma_{X-1}}^{\sigma'_0,\sigma_2,\cdots,\sigma'_{X-1}} =&
(A_0 ^ {\sigma_0})_{v_1}
\cdots
(A_{X-1} ^ {\sigma_{X-1}})_{v_{X-1} v_X}
\\
&
M_{v_X, v_X'}
\\
&
(A_0 ^ {\sigma'_0})^\dag_{v'_1}
\cdots
(A_{X-1} ^ {\sigma'_{X-1}})^\dag_{v'_{X-1} v'_X},
\end{aligned}
\end{equation}
其中
\begin{equation}
\begin{aligned}
M_{v_X, v_X'} =&
(A_X ^ {\sigma_X})_{v_X v_{X+1}}
\cdots
(A_{L-1} ^ {\sigma_{N-1}})_{v_{N-1}}
\\
&
(A_X ^ {\sigma_X})^\dag_{v'_X v'_{X+1}}
\cdots
(A_{L-1} ^ {\sigma_{N-1}})^\dag_{v'_{N-1}} ,
\end{aligned}
\end{equation}
而 $M_{v_X,v'_X}$ 是一个 $D \times D$ 的矩阵，所以密度矩阵 $\hat \rho_X$ 的秩不大于 $D$ ，则其可表示的最大纠缠熵为 $S = \ln D$ ，即一个常数。
而满足纠缠熵面积定律的一维系统，两部分的边界是零维的点，大小也是常数，所以MPS表示的一维系统恰好是满足一维情况下面积定律的系统。

由于MPS对面积定律恰到好处的展示，MPS可以较高效地表示满足纠缠熵面积定律的系统的波函数。
一维情况下，局部哈密顿量构成的有能隙系统的基态是满足面积定律的，所以一个固定 $D$ 的MPS可以很好地表示其基态。
而对于无能隙的系统，有 $S \propto \alpha \ln L$ ，即纠缠熵随着系统的尺寸对数上升，而 $ S \propto \ln D$ ，所以应取 $D \propto L ^\alpha$ ，
对于 $\alpha$ 较小的情况， 所需的 $D$ 随着系统尺寸增长缓慢，我们依然可以通过计算相当大的系统来了解接近热力学极限时系统的性质。

*** 张量网络的图形标记

由于张量网络态中各个张量通常有复杂的运算关系，使用爱因斯坦求和约定不能直观地展示张量之间的关系，人们通常使用图形标记法来表示一张张量网络。
图形标记法中，使用一个闭合的图形表示一个张量，图形上的每一条线表示张量的一个指标，两个张量之间彼此相连的线表示这两个指标将要求和。
图 [[ref:fig:张量的图形标记法]] 中展示了一些基本的例子。

#+begin_export latex
\begin{figure}
\centering
\input{tikz/graphical_notation.tikz}
\caption{张量的图形标记法}
\label{fig:张量的图形标记法}
\note{注：
(a)是一个标量 $A$ ，即0阶张量；
(b)是一个向量 $A_i$ ，即1阶张量，有一个指标 $i$ ；
(c)是一个矩阵 $A_{ij}$ ，即2阶张量，有两个指标 $i$ 和 $j$ ；
(d)表示矩阵 $A_{ij}$ 和向量 $B_j$ 的乘积，即 $A_{ij} B_{j}$ ；
(e)表示两个矩阵相乘，即 $A_{ij} B_{jk}$ ；
(f)中三个矩阵彼此相连，表示了 $A_{ij} B_{jk} C_{ji}$ 。
}
\end{figure}
#+end_export

使用图形标记法表示的公式 [[eqref:eq:一维系统波函数的MPS展开]] 所展示的MPS在 $L=5$ 时如图 [[ref:fig:图形标记法表示的长度为5的MPS]] 所示。
张量网络的图形标记法直观地展示了张量之间的连接关系。

#+begin_export latex
\begin{figure}
\centering
\input{tikz/mps.tikz}
\caption{图形标记法表示的长度为$5$的MPS}
\label{fig:图形标记法表示的长度为5的MPS}
\end{figure}
#+end_export

** 投影纠缠对态 (PEPS)

*** PEPS的表示

MPS成功地处理一维系统后，有一些将MPS直接应用于二维系统的尝试，如图 [[ref:fig:用于表示二维系统的MPS和PEPS]] (a)所示。
但是二维系统中，对于满足纠缠熵面积定律的系统，纠缠熵 $S \propto L$ ，其中 $L$ 为边界的长度。
这意味这MPS的 $D$ 需要随着系统增大而增大。
时至今日，这种方法通常被用于长条形的系统的求解，而对于真正的二维系统，MPS无法胜任。
Verstraete在表示二维系统的MPS上额外上了行间的边从而得到了PEPS [[cite:Verstraete2004]] ，如图 [[ref:fig:用于表示二维系统的MPS和PEPS]] (b)所示。
我们称呼物理指标所在的边为物理边，其他张量之间彼此相连的边为虚拟边。

#+begin_export latex
\begin{figure}
\centering
\input{tikz/mps_to_peps.tikz}
\caption{用于表示二维系统的MPS和PEPS}
\label{fig:用于表示二维系统的MPS和PEPS}
\note{注：由于固定 $D$ 的MPS只能表示常数的纠缠熵，通过在行间加上而外的边可以得到PEPS，PEPS可以满足二维系统的面积定律。}
\end{figure}
#+end_export

一张PEPS中划分出一个区域X，其与外界相连的边的数目正比与区域的周长，即边的数目 $N \propto |\partial X|$ 。
类似MPS的情况，计算约化密度矩阵时有同样的形式：
\begin{equation}\label{eq:PEPS中计算约化密度矩阵}
(\hat\rho_{X})_{s_{X, 0}, s_{X, 1}, \cdots} ^ {s'_{X, 0}, s'_{X, 1}, \cdots} =
T_{s_{X,0}, s_{X,1}, \cdots}^{v_0, v_1, \cdots v_{N-1}}
M_{v_0, v_1, \cdots v_{N-1}}^{v'_0, v'_1, \cdots v'_{N-1}}
T^{\dagger {s'_{X,0}, s'_{X,1}, \cdots}}_{v'_0, v'_1, \cdots v'_{N-1}} , 
\end{equation}
其中， $s_{X,i}$ 为区域X中各个物理指标， $v_i$ 为区域X和外部相连的边的指标。
公式 [[eqref:eq:PEPS中计算约化密度矩阵]] 中间有一个 $D^N$ 维度的矩阵$M$，其中 $D$ 是PEPS中虚拟边的维度。
而 $S = \ln D^N = N \ln D \propto |\partial X|$ ，所以PEPS可以满足二维系统的纠缠熵面积定律。

*** 投影纠缠对

使用一张张量网络表示波函数时，我们可以有两种阐述方式。第一种是数学上的分解，即对于任意一个 $R$ 个粒子的系统，波函数
\begin{equation}
|\Psi\rangle = T_{i_{T,0}, i_{T,1}, \cdots, i_{T,R-1}} |i_0 i_1 \cdots i_{R-1} \rangle ,
\end{equation}
中 $T$ 作为一个 $R$ 阶张量，可以被分解为一张张量网络：
\begin{equation}
\begin{aligned}
T_{i_{T,0}, i_{T,1}, \cdots, i_{T, R-1}} = &
\prod_{n=0}^{N-1} (A_n)_{i_{A_n, 0} i_{A_n, 1} \cdots i_{A_n, \mathrm{rank}(A_n) -1}}
\\ &
\prod_{b=0}^{B-1} \delta^{i_{A_{V_b^0},E_b^0}}_{i_{A_{V_b^1},E_b^1}}
\\ &
\prod_{r=0}^{R-1} \delta^{i_{T,r}}_{i_{A_{V'_r},E'_r}} .
\end{aligned}
\end{equation}
这张张量网络中有 $N$ 个张量，即 $A_n$ ，其中 $n = 0, 1, \cdots N-1$ 。
张量 $A_n$ 的阶数是 $\mathrm{rank}(A_n)$ ，它的指标被记作 $i_{A_n, j}$ ，其中 $j = 0, 1, \cdots \mathrm{rank}(A_n) - 1$ 。
这张张量网络内部有 $B$ 个边连接两个张量，第 $b$ 个边所连接的是第 $V_b^0$ 个张量的第 $E_b^0$ 个边和第 $V_b^1$ 个张量的第 $E_b^1$ 个边，其中 $b=0,1,\cdots B-1$
而这些张量中，有 $R$ 个边没有被收缩，而是作为物理边出现在张量 $T$ 中，
张量 $T$ 的第 $r$ 个边在张量网络中是第 $V'_r$ 个张量的第 $E'_r$ 个边，其中 $r = 0, 1, \cdots R-1$ 。
这张张量网络中，由 $A_n$ ， $n=0, \cdots N-1$ 组成，由 $V_b^0, V_b^1, V'_r, E_b^0, E_b^1, E'_r$ ， $b=0,\cdots B-1, r=0,\cdots R-1$ 表示张量的图结构。
通过不同的张量网络图结构，可以构造出不同类型的张量网络。

另一种阐述方式是将张量网络态视为对一群纠缠对所构成的母态的投影。
先把波函数写成产生算符的形式：
\begin{equation}\label{eq:一般的波函数}
|\Psi\rangle = T_{i_{T,0}, i_{T,1}, \cdots, i_{T,R-1}} \prod_{r=0}^{R-1} c_r^{\dag i_{T,r}} |\Omega\rangle ,
\end{equation}
其中 $|\Omega\rangle$ 是真空态，  $c_r^{\dag i_{T,r}}$ 是第 $r$ 个粒子处，产生第 $i_{T,r}$ 个构型的算符。
需要注意的是，对于一些系统， $c_r^{\dag i_{T,r}}$ 不一定是单个粒子的产生算符，而可能是多个粒子产生算符的复合。
然后将波函数视为对一个母态的投影：
\begin{equation}
|\Psi\rangle = P M |\Omega\rangle ,
\end{equation}
其中 $P$ 为投影算符， $M$ 为制备母态的算符。
而母态为众多组纠缠对的组合：
\begin{equation}
M = 
\prod_{b=0}^{B-1} a_{b,0}^{\dag d_b} a_{b,1}^{\dag d_b}
,
\end{equation}
其中第 $b$ 组纠缠对由 $a_{b,0}^{\dag d_b}$ 和 $a_{b,1}^{\dag d_b}$ 生成， 这里 $d_b$ 取值范围为 $0, 1, \cdots D_b - 1$ ，其中 $D_b$ 为这组纠缠对的个数。
而投影算符被定义为：
\begin{equation}
\begin{aligned}
P = 
\prod_{n=0}^{N-1} & (A_n)_{i_{A_n, 0} i_{A_n, 1} \cdots i_{A_n, \mathrm{rank}(A_n) -1}} \\
&
\prod_{j=0}^{\mathrm{rank}(A_n) - 1} \left\{
\begin{aligned}
&a^{i_{A_n, j}}_{X_{A_n,j},Y_{A_n, j}} \ & \text{如果 $A_n$ 的第 $j$ 个边为虚拟边}, \\
&c^{\dag i_{A_n,j}}_{Z_{A_n,j}} \ & \text{如果 $A_n$ 的第 $j$ 个边为物理边},
\end{aligned}
\right.
\end{aligned}
\end{equation}
其中 $A_n$ 的第 $j$ 个边，如果是物理边，则是 $|\Psi\rangle$ 的第 $Z_{A_n,j}$ 个边，
如果是虚拟边，则将湮灭掉第 $X_{A_n,j}$ 组纠缠对中粒子，而 $Y_{A_n,j}$ 取 $0$ 或 $1$ ，标记其湮灭的是纠缠对中靠前的还是靠后的粒子。
这种解释方式中，将张量网络的虚拟边用纠缠对表示，投影算子中湮灭同一个纠缠对的两个部分是彼此相连的张量。
每个张量通过湮灭掉纠缠对并产生物理的粒子，实现了将多组纠缠对投影到物理空间的操作，这便是投影纠缠对态的名称由来。
值得注意的是，虽然对纠缠对的投影可以阐述任意图结构的张量网络，但是我们提到“投影纠缠对态”时，都是特指方格形的张量网络的。

在张量网络态的投影纠缠对阐述中，投影部分既有湮灭算符也有产生算符，这不够好看。
我们可以再引入一个虚拟的粒子，得到：
\begin{equation}
\left\{
\begin{aligned}
P &= 
\prod_{n=0}^{N-1} (A_n)_{i_{A_n, 0} i_{A_n, 1} \cdots i_{A_n, \mathrm{rank}(A_n) -1}}
\prod_{j=0}^{\mathrm{rank}(A_n) - 1} 
a^{i_{A_n, j}}_{X_{A_n,j},Y_{A_n, j}} , \\
M &=
\prod_{b=0}^{B-1} a_{b,0}^{\dag d_b} a_{b,1}^{\dag d_b}
\prod_{r=0}^{R-1} a_{r+B,0}^{\dag d_{r+B}} c_r^{\dag d_{r+B}} ,
\end{aligned}
\right.
\end{equation}
这样我们依然可以将公式 [[eqref:eq:一般的波函数]] 表示为母态上的投影，即 $|\Psi\rangle = P M |\Omega\rangle$ 。
这种变型的投影纠缠对阐述将每个张量中各个边平等地对待，图结构的信息完全放置在母态生成算符 $M$ 中。

** 对称性张量和费米子张量

当一个系统的哈密顿量拥有某个对称性时，其基态要么满足这个对称性，要么自发破缺从而是简并的。
对称性变换使用一个紧致群 $G$ 来描述，
如果公式 [[eqref:eq:一般的波函数]] 表示的基态波函数满足这个对称性，我们有
\begin{equation}\label{eq:对称性张量}
U_g^{\otimes R} T_{i_{T,0},\cdots, i_{T,R-1}} = T_{i_{T,0},\cdots, i_{T,R-1}} ,
\end{equation}
其中 $g \in G$ ，
$U_g^{\otimes R} = \bigotimes_{r=0}^{R-1} U_g^r$ ， $U_g^r$ 为 $g$ 在张量的第 $r$ 个指标的线性空间上的表示。
满足公式 [[eqref:eq:对称性张量]] 的张量被称作对称性张量 [[cite:Singh2010]] ，图 [[ref:fig:对称性张量和对称性张量网络]] (a)使用图形标记法展示了此关系。
需要注意对称性张量和对称矩阵完全不同，对称矩阵是做交换两个指标的转置变换下不变的矩阵，对称性张量是在每个指标中各自做相同的群元素代表的群变换下不变的张量。

#+begin_export latex
\begin{figure}
\centering
\input{tikz/symmetry.tikz}
\caption{对称性张量和对称性张量网络}
\label{fig:对称性张量和对称性张量网络}
\note{注：
(a)中，对张量做一个对称性变换相当与在张量的每个指标上作用上这个指标上 $g$ 的群表示矩阵，因为是群是紧致的，我们可以给张量找到一组合适的基使得矩阵是酉的。
(b)中，如果张量网络中的每个张量都是对称性张量，我们可以在每个张量的周围都加上群的变换矩阵，而不改变张量网络的值，得到等式的左侧；
而两个张量彼此相互收缩的线性空间是相互共轭的，所以他们的群表示是互逆的，所有的虚拟边上的两个矩阵可以相互抵消而不改变张量网络的值，得到等式的右侧；
所以原有的张量网络等于只在物理边上做群变换，即整个张量网络的收缩结果是对称性张量。}
\end{figure}
#+end_export

波函数的物理指标有明确的物理意义，所以给定对称群的群表示是固定的。
而对于一个张量网络态，我们可以将每个虚拟指标所在的线性空间也看作对称群的一个表示空间，
从而我们可以对张量网络态中的每个张量各自做对称性变换。
值得注意的是，这种虚拟指标所在空间的群表示是任意的。
从图 [[ref:fig:对称性张量和对称性张量网络]] (b) 中可以很明显看出，对称性张量收缩结果仍然是对称性张量。

一个对称性张量的每个边所在的空间都是群的表示空间，空间 $V$ 可以分解为
\begin{equation}
V \cong \bigoplus_{s} d_s V^{s} \cong \bigoplus_{s} (D^{s} \otimes V^{s}),
\end{equation}
其中 $V^s$ 是群的第 $s$ 个不可约表示空间， $d_s$ 是他的重数，这里 $D^s$ 是 $d_s$ 维的简并空间。

我们可以使用 $U_g^r$ 来作张量的第 $r$ 个指标的基，每个指标的空间 $V^r = \bigoplus_s (D^{r,s} \otimes V^s)$ 中，使用 $(s,\alpha_s, m_s)$ 来作为基底。
其中 $s$ 标记了不同的不可约表示， $\alpha_s$ 是简并空间的指标，即 $\alpha_s = 0,1,\cdots d_s-1$ ，而 $m_s$ 是这个不可约表示空间中的指标。

在这个基下，一个张量是一个对称性张量的条件是
+ 0阶 :: 标量显然是一个对称性张量。
+ 1阶 :: 其非零元素只能位于平凡的不可约表示中，即 $s=0$ ，而 $m_0=0$ 。
+ 2阶 :: 其非零元素的两个指标需要在相同的不可约表示空间中，且两者的 $m_s$ 相反，即张量需要满足形式
\begin{equation}
T_{(s_0,\alpha_{s_0},m_{s_0}),(s_1,\alpha_{s_1},m_{s_1})} =
P_{(s_0,\alpha_{s_0}),(s_1,\alpha_{s_1})} \delta_{s_0,s_1}
\begin{pmatrix} s_0 \\ m_{s_0} \quad m_{s_1} \end{pmatrix},
\end{equation}
其中括号是Wigner 1-jm符号。
+ 3阶 :: 张量需要满足形式
\begin{equation}
T_{(s_0,\alpha_{s_0},m_{s_0}),(s_1,\alpha_{s_1},m_{s_1}),(s_2,\alpha_{s_2},m_{s_2})} =
P_{(s_0, \alpha_{s_0}),(s_1, \alpha_{s_1}),(s_2, \alpha_{s_2})}
\begin{pmatrix}
s_0 & s_1 & s_2 \\
m_0 & m_1 & m_2
\end{pmatrix},
\end{equation}
其中括号是Wigner 3-jm符号。
+ 更高阶 :: 张量需要可以被分解为多个3阶对称性张量收缩的形式。

如上所示，一般对称群的对称性张量结构十分复杂，但对于Abel群来说，情况却十分简单。
Abel群的不可约表示一定是1维的，所以恒有 $m_s=0$ ,故我们将 $m_s$ 省略，使用 $(s,\alpha_s)$ 作为基。
此时 $R$ 阶的对称性张量需要满足
\begin{equation}
U_g^{\otimes R} T_{(s_0,\alpha_{s_0}),(s_1,\alpha_{s_1}),\cdots (s_{R-1},\alpha_{s_{R-1}})} =
T_{(s_0,\alpha_{s_0}),(s_1,\alpha_{s_1}),\cdots (s_{R-1},\alpha_{s_{R-1}})},
\end{equation}
而 $U_g^{\otimes R}$ 中每个项目 $U_g^r = U_g^{s_r}$ ，作为一个一维的酉矩阵，就是一个复数。
所以我们得到：
\begin{equation}
T_{(s_0,\alpha_{s_0}),(s_1,\alpha_{s_1}),\cdots (s_{R-1},\alpha_{s_{R-1}})}
\prod_r^{R-1}U_g^{s_r}
=
T_{(s_0,\alpha_{s_0}),(s_1,\alpha_{s_1}),\cdots (s_{R-1},\alpha_{s_{R-1}})}.
\end{equation}
为此，张量需要满足形式：
\begin{equation}\label{eq:Abel对称张量的原始形式}
T_{(s_0,\alpha_{s_0}),(s_1,\alpha_{s_1}),\cdots (s_{R-1},\alpha_{s_{R-1}})} =
P_{(s_0, \alpha_{s_0}),(s_1, \alpha_{s_1}),\cdots (s_{R-1}, \alpha_{s_{R-1}})}
C(s_0,s_1,\cdots s_{R-1}) ,
\end{equation}
其中
\begin{equation}
C(s_0, s_1, \cdots s_{R-1}) = \left\{\begin{aligned}
1 \quad & \text{如果对于任意$g$有}  \quad \prod_r^{R-1} U_g^{s_r} = 1 ,\\
0 \quad & \text{其他情况},
\end{aligned}\right.
\end{equation}
是对称群决定的对称性条件。
将公式 [[eqref:eq:Abel对称张量的原始形式]] 稍作变形得到：
\begin{equation}
T_{(s_0,\alpha_{s_0}),(s_1,\alpha_{s_1}),\cdots (s_{R-1},\alpha_{s_{R-1}})} =
\left(P_{s_0,s_1,\cdots,s_{R-1}}\right)_{\alpha_{s_0},\alpha_{s_1},\cdots \alpha_{s_{R-1}}}
R(s_0,s_1,\cdots s_{R-1}) .
\end{equation}
可见Abel群的对称性张量是一个分块的张量，其中分块方案由对称性条件和张量每个边上的不可约表示分解决定。

物理中常见的群是 $Z(2)$ 群和 $U(1)$ 群。
对于 $Z(2)$ 群， $g=e$ 表示不变， $g=z$ 表示反转。
群表示 $0$ 中 $U_e^0 = U_z^0 = +1$ ，另一个群表示 $1$ 中 $U_e^1 = +1$ ， $U_z^1 = -1$ 。
所以 $Z(2)$ 群的对称性条件是：
\begin{equation}
C(s_0, s_1, \cdots s_{R-1}) = \left\{\begin{aligned}
1 \quad & \text{如果}  \quad \bigoplus_r^{R-1} s_r = 0 ,\\
0 \quad & \text{如果}  \quad \bigoplus_r^{R-1} s_r = 1 ,
\end{aligned}\right.
\end{equation}
其中 $\bigoplus$ 为异或运算。

而对于 $U(2)$ 群， $g=\theta$ 表示旋转 $\theta$ 。
群表示使用一个整数 $s$ 来标记， $U_\theta^s = \mathrm{e}^{\mathrm{i} s \theta}$ 。
所以 $U(1)$ 群的对称性条件是：
\begin{equation}
C(s_0, s_1, \cdots s_{R-1}) = \left\{\begin{aligned}
1 \quad & \text{如果}  \quad \sum_r^{R-1} s_r = 0 ,\\
0 \quad & \text{如果}  \quad \sum_r^{R-1} s_r \neq 0 .
\end{aligned}\right.
\end{equation}

* 张量网络态的优化方法 <<sec:张量网络态的优化方法>>

** 虚时间演化算法

** 采样方法与基于采样方法的变分法

#+begin_export latex
\bibliography{main}
\appendix
#+end_export

#+begin_export latex
\backmatter
#+end_export

#+begin_export latex
\begin{acknowledgements}
在研究学习期间，我有幸得到了三位老师的教导，
他们是：我的导师，中国科大XXX研究员，中科院X昆明动物所马老师以及美国犹他大学的XXX老师。
三位深厚的学术功底，严谨的工作态度和敏锐的科学洞察力使我受益良多。
衷心感谢他们多年来给予我的悉心教导和热情帮助。

感谢XXX老师在实验方面的指导以及教授的帮助。
科大的XXX同学和XXX同学参与了部分试验工作，在此深表谢意。

TODO
\end{acknowledgements}

\begin{publications}

\section*{已发表论文}

\begin{enumerate}
\item A A A A A A A A A
\item A A A A A A A A A
\item A A A A A A A A A
\end{enumerate}

\section*{待发表论文}

\begin{enumerate}
\item A A A A A A A A A
\item A A A A A A A A A
\item A A A A A A A A A
\end{enumerate}

\section*{研究报告}
\begin{enumerate}
\item A A A A A A A A A
\item A A A A A A A A A
\item A A A A A A A A A
\end{enumerate}

TODO
\end{publications}
#+end_export
